- kafka-instrumentation/build.gradle.kts
- kafka-instrumentation/src/main/java/dev/responsive/kafka/clients/ResponsiveConsumer.java
- kafka-instrumentation/src/main/java/dev/responsive/kafka/clients/ResponsiveProducer.java
- kafka-instrumentation/src/test/java/dev/responsive/kafka/clients/ResponsiveConsumerTest.java
- kafka-instrumentation/src/test/java/dev/responsive/kafka/clients/ResponsiveProducerTest.java
- settings.gradle.kts
Add a consumer/producer that wraps a real consumer/producer and notifies listeners on events of interest. The consumer notifies listeners about subscription assignment changes. The producer notifies listeners about commits
> add responsive client shims

- operator/src/main/java/dev/responsive/k8s/operator/reconciler/DemoPolicyPlugin.java
- operator/src/main/java/dev/responsive/k8s/operator/reconciler/ManagedApplication.java
- operator/src/test/java/dev/responsive/k8s/operator/reconciler/DemoPolicyPluginTest.java
Update the operator to support statefulsets.
> Add StatefulSet support to the operator

- kafka-instrumentation/src/main/java/dev/responsive/kafka/clients/EndOffsetsPoller.java
- kafka-instrumentation/src/main/java/dev/responsive/kafka/clients/ResponsiveConsumer.java
- kafka-instrumentation/src/main/java/dev/responsive/kafka/clients/ResponsiveKafkaClientSupplier.java
- kafka-instrumentation/src/test/java/dev/responsive/kafka/clients/ResponsiveKafkaClientSupplierTest.java
Just opening a mock PR to facilitate review of https://github.com/responsivedev/responsive-pub/pull/34
This shows [PR #34](https://github.com/responsivedev/responsive-pub/pull/34) relative to [PR #33](https://github.com/responsivedev/responsive-pub/pull/33)
> add responsive client supplier for publishing metrics

- operator/src/main/java/dev/responsive/k8s/operator/reconciler/DemoPolicyPlugin.java
- operator/src/main/java/dev/responsive/k8s/operator/reconciler/ManagedApplication.java
- operator/src/main/java/dev/responsive/k8s/operator/reconciler/ManagedDeployment.java
- operator/src/main/java/dev/responsive/k8s/operator/reconciler/ManagedStatefulSet.java
> Refactor ManagedApplication into ManagedDeployment and ManagedStatefulSet.

- etc/otel-jmx.config.yaml
Baseline set of metrics I would like to include
> Add Kafka Streams and client metrics

- kafka-client/src/main/java/dev/responsive/db/CassandraClient.java
- kafka-client/src/main/java/dev/responsive/kafka/store/CommitBuffer.java
- kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveGlobalStore.java
- kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveStore.java
- kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveWindowStore.java
minor commit to add more logging to the state stores - we should still integrate with the the datastax driver query logger so that we can have more details there. There's also server-side logging we can enable.
> add more logging

- operator/src/main/java/dev/responsive/k8s/operator/reconciler/ManagedDeployment.java
- operator/src/main/java/dev/responsive/k8s/operator/reconciler/ManagedStatefulSet.java
- operator/src/test/java/dev/responsive/k8s/operator/reconciler/DemoPolicyPluginTest.java
Fixes a bug in code that patches deployment/sts resoruces. The app client returned in the context should not be closed - as its owned by the framework and is long-lived. If its closed, the next thing that tries to use it will fail
> dont close appClient when patching deployment/sts

- kafka-client/src/main/java/dev/responsive/db/CassandraClient.java
- kafka-client/src/main/java/dev/responsive/kafka/store/AtomicWriteResult.java
- kafka-client/src/main/java/dev/responsive/kafka/store/AtomicWriter.java
- kafka-client/src/main/java/dev/responsive/kafka/store/BufferPlugin.java
- kafka-client/src/main/java/dev/responsive/kafka/store/CommitBuffer.java
- kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveStore.java
- kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveWindowStore.java
- kafka-client/src/test/java/dev/responsive/kafka/store/AtomicWriterTest.java
move code around and use `CompletionStage` to set up for the virtual partition PR
> refactor CommitBuffer to use async calls

- kafka-client/src/main/java/dev/responsive/kafka/clients/MetricPublishingCommitListener.java
> change log level for on commit

- kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
confirmed that you can pass in `Properties` where `Map<?, ?>` is expected
> support creating ResponsiveKafkaStreams via Properties instead of Map

- .github/workflows/github-publish.yaml
Runs smoke tests during publish, and promotes sindri operator/clients versions, if the version is newer
> run smoke tests during publish and promote

- .github/workflows/github-publish.yaml
Reverts responsivedev/responsive-pub#86
> Revert "run smoke tests during publish and promote"

- kafka-client/src/main/java/dev/responsive/kafka/store/CommitBuffer.java
- kafka-client/src/main/java/dev/responsive/kafka/store/ResponsivePartitionedStore.java
- kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveWindowStore.java
- kafka-client/src/test/java/dev/responsive/kafka/store/SubPartitionIntegrationTest.java
we shouldn't be using the subpartitioner if we're running with the fact table schema
> fix subpartitioner usage with Fact table schema

- kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
- kafka-client/src/main/java/dev/responsive/kafka/clients/ResponsiveKafkaClientSupplier.java
- kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveRestoreListener.java
- kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveStoreRegistration.java
- kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveStoreRegistry.java
- kafka-client/src/test/java/dev/responsive/kafka/clients/ResponsiveKafkaClientSupplierTest.java
Sets a StateRestoreListener that logs or delegates to the user's listener if one exists. Also includes some minor refactoring to pass the `Metrics` in, though no actual metrics are added just yet
> metrics: set up a StateRestoreListener 

- .github/workflows/github-main.yaml
- .github/workflows/github-pr.yaml
- .github/workflows/github-publish.yaml
- buildSrc/src/main/kotlin/responsive.docker.gradle.kts
run clean before building docker images. This ensures you dont get multiple versions of the jars on the classpath of the image
> clean before docker build

- .github/actions/aws-and-ecr-login/action.yaml
- .github/workflows/github-main.yaml
- .github/workflows/github-pr.yaml
- .github/workflows/github-publish.yaml
Pure formatting: make sure to name all steps, including checkouts, and apply double quotation formatting to all names and strings.
> Name all steps and format strings

- etc/otel-jmx.config.yaml
Could have sworn I added this already but I don't see it, so...
Good to have
> Add `assigned-partitions` consumer metric

- kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveGlobalStore.java
Extracting this fix to its own PR as suggested here https://github.com/responsivedev/responsive-pub/pull/153#discussion_r1343070475
> Treat null-value puts as deletes in ResponsiveGlobalStore

- kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/ApplicationMetrics.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/OrderedTagsSupplier.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/ResponsiveMetrics.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/StoreMetrics.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/TopicMetrics.java
- kafka-client/src/test/java/dev/responsive/kafka/internal/metrics/OrderedTagsSupplierTest.java
Minor followup to https://github.com/responsivedev/responsive-pub/pull/156
See https://github.com/responsivedev/responsive-pub/pull/156#discussion_r1348442860
> Add OrderedTagsSupplier to maintain metrics tag ordering 

- etc/otel-jmx.config.yaml
- kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/ResponsiveMetrics.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/ResponsiveRestoreListener.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/StoreMetrics.java
- kafka-client/src/test/java/dev/responsive/kafka/internal/metrics/ResponsiveRestoreListenerTest.java
Minor followup to https://github.com/responsivedev/responsive-pub/pull/167 (see [this comment](https://github.com/responsivedev/responsive-pub/pull/167#discussion_r1358960863) for context)
> Switch restore latency metric from sensor to gauge

- kafka-client/build.gradle.kts
- kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/ResponsiveMetrics.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/exporter/MetricsExportService.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/exporter/NoopMetricsExporterService.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/exporter/otel/OtelMetricsService.java
- kafka-client/src/test/java/dev/responsive/kafka/internal/metrics/EndOffsetsPollerTest.java
- kafka-client/src/test/java/dev/responsive/kafka/internal/metrics/MetricPublishingCommitListenerTest.java
- kafka-client/src/test/java/dev/responsive/kafka/internal/metrics/ResponsiveRestoreListenerTest.java
- kafka-client/src/test/java/dev/responsive/kafka/internal/stores/CommitBufferTest.java
- responsive-test-utils/src/main/java/dev/responsive/kafka/internal/stores/TTDRestoreListener.java
some minor changes:
1. address @rodesai's feedback on #191 
2. use `ApiKeyHeader` constants
3. fix bug where I was passing in the ApiKey as the secret
4. allow for metrics w/o authentication
> follow up for agent-free metrics

- kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/EndOffsetsPoller.java
- kafka-client/src/test/java/dev/responsive/kafka/internal/metrics/EndOffsetsPollerTest.java
dont bubble up offset polling errors. If we do, then the poller makes no more attempts to poll. Instead, just log the error and the poller will retry on the next iteration. If its still failing after 3 iterations, it reinitializes the admin client.
> dont bubble up offset polling errors

- kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoKVTable.java
Minor improvement to clear up a somewhat confusing tactic of saving a map of MetadataDocs per partition when we only need to save the epoch per partition instead.
> Use kafkaPartition for ObjectId in MongoKVTable

- operator/docker/Dockerfile
- operator/src/main/helm/templates/deployment.yaml
- operator/src/main/helm/values.yaml
- fix indentation on security context entries
- bump debian version to pick up some cve fixes
> fix more operator issues

- kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
- kafka-client/src/main/java/dev/responsive/kafka/api/config/ResponsiveConfig.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/CollectionCreationOptions.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoConstants.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoKVTable.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoUtils.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoWindowedTable.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoWriter.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/ResponsiveMongoClient.java
- kafka-client/src/test/java/dev/responsive/kafka/integration/ResponsiveKeyValueStoreRestoreIntegrationTest.java
- kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoKVTableTest.java
- kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoWriterTest.java
Adds support for sharding mongodb collections. Sharding is enabled using a config property
> add support for sharding mongodb collections

- kafka-client/src/main/java/dev/responsive/kafka/internal/utils/SessionUtil.java
see https://www.mongodb.com/docs/atlas/troubleshoot-connection/#special-characters-in-connection-string-password
> URL encode mongo username/password

- kafka-client/src/main/java/dev/responsive/kafka/api/config/ResponsiveConfig.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraClient.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraFactTable.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraKeyValueTable.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraWindowedTable.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/db/QueryOp.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/utils/SessionUtil.java
- kafka-client/src/test/java/dev/responsive/kafka/integration/MinimalIntegrationTest.java
- kafka-client/src/test/java/dev/responsive/kafka/internal/db/CassandraClientTest.java
- responsive-test-utils/src/main/java/dev/responsive/kafka/internal/clients/TTDCassandraClient.java
> set default consistency level to quourm with ability to override

- kafka-client/src/test/java/dev/responsive/kafka/integration/ResponsiveSessionStoreIntegrationTest.java
Discussed offline, @apourchet will fix this tomorrow. Disabling for now to unblock build.
> disable flaky session integration test

- controller-api/src/main/proto/responsive/controller/v1/controller.proto
- operator/src/main/java/dev/responsive/k8s/crd/PolicyCooldownSpec.java
- operator/src/main/java/dev/responsive/k8s/crd/ResponsivePolicySpec.java
- operator/src/main/java/dev/responsive/k8s/crd/kafkastreams/DemoPolicySpec.java
- operator/src/main/java/dev/responsive/k8s/crd/kafkastreams/KafkaStreamsPolicySpec.java
- operator/src/test/java/dev/responsive/k8s/controller/ControllerProtoFactoriesTest.java
- operator/src/test/java/dev/responsive/k8s/crd/ResponsivePolicySpecTest.java
- operator/src/test/java/dev/responsive/k8s/operator/reconciler/KafkaStreamsPolicyPluginTest.java
- operator/src/test/java/dev/responsive/k8s/operator/reconciler/ResponsivePolicyReconcilerTest.java
This lets the user decide how often the controller should try to scale
up or down the application.
> CRD: Added a coolown field to the policy spec

- kafka-client/src/main/java/dev/responsive/kafka/internal/stores/SessionOperationsImpl.java
- kafka-client/src/test/java/dev/responsive/kafka/integration/ResponsiveSessionStoreIntegrationTest.java
Also locally tested with infinite commit buffer.
> Integration Tests: Fix session store integration test

- kafka-client/src/test/java/dev/responsive/kafka/async/AsyncProcessorIntegrationTest.java
- kafka-client/src/test/java/dev/responsive/kafka/testutils/IntegrationTestUtils.java
- kafka-client/src/test/java/dev/responsive/kafka/testutils/SimpleStatefulProcessor.java
- kafka-client/src/test/java/dev/responsive/kafka/testutils/SimpleStatefulProcessorSupplier.java
Here's the final form of the baseline integration test (will open a separate PR for the strictly-new tests being added). This adds all the planned "toggles" and consolidates all parameters up top for a quick modifications and runs of the test. Will publish the test log of what I've run so far with these toggles.
> Async integration test toggles and improvements

- kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncProcessor.java
- kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncThreadPool.java
- kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/queues/FinalizingQueue.java
- kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/queues/KeyOrderPreservingQueue.java
- kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/queues/MeteredSchedulingQueue.java
- kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/queues/SchedulingQueue.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/stores/CommitBuffer.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveStoreRegistry.java
Reverts responsivedev/responsive-pub#318
> Revert "some logging and assertions we added for antithesis tests"

- .github/workflows/github-e2e.yaml
- .gitignore
- kafka-client-examples/e2e-test/build.gradle.kts
- kafka-client-examples/e2e-test/docker/Dockerfile
- kafka-client-examples/e2e-test/docker/antithesis/Dockerfile
- kafka-client-examples/e2e-test/docker/antithesis/config/docker-compose.yml.template
- kafka-client-examples/e2e-test/docker/antithesis/config/volumes/app.properties
- kafka-client-examples/e2e-test/docker/antithesis/config/volumes/log4j2.properties
- kafka-client-examples/e2e-test/docker/antithesis/config/volumes/scylla.yaml
- kafka-client-examples/e2e-test/docker/scripts/run-e2etest
- kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/e2etest/AccumulatingChecksum.java
- kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/e2etest/E2ETestApplication.java
- kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/e2etest/E2ETestDriver.java
- kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/e2etest/E2ETestUtils.java
- kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/e2etest/Main.java
- kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/e2etest/Params.java
- kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/e2etest/Schema.java
- kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/e2etest/UrandomGenerator.java
- kafka-client-examples/e2e-test/src/main/resources/log4j2.properties
- kafka-client-examples/e2e-test/src/test/java/dev/responsive/examples/e2etest/AccumulatingChecksumTest.java
- kafka-client-examples/e2e-test/src/test/java/dev/responsive/examples/e2etest/ResponsiveConfigParam.java
- kafka-client-examples/e2e-test/src/test/java/dev/responsive/examples/e2etest/ResponsiveE2EApplicationTestExtension.java
- kafka-client-examples/e2e-test/src/test/java/dev/responsive/examples/e2etest/TestApplicationIntegrationTest.java
- kafka-client-examples/e2e-test/src/test/resources/CassandraDockerInit.cql
- kafka-client-examples/e2e-test/src/test/resources/junit-platform.properties
- kafka-client-examples/e2e-test/src/test/resources/log4j2-test.properties
- kafka-client-examples/e2e-test/src/test/resources/testcontainers.properties
- settings.gradle.kts
Adds an application for doing end to end tests using antithesis:
- Add a test application and driver. The application uses the async processor and computes a runnin checksum of all the records received with a given key. The driver produces records and verifies that the computed checksums are correct.
- Packages up the test application into a docker image
- Also builds an antithesis config image that stands up a self-contained environment for running the application using docker-compose.
- Updates the e2e test workflow file to kick off antithesis test runs.
> add antithesis test application

- .github/workflows/github-pr.yaml
- kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncProcessor.java
- kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncProcessorId.java
- kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncThreadPool.java
- kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncThreadPoolRegistration.java
- kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/events/AsyncEvent.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/clients/AsyncStreamsProducer.java
- kafka-client/src/test/java/dev/responsive/kafka/api/async/internals/AsyncThreadPoolTest.java
- kafka-client/src/test/java/dev/responsive/kafka/async/AsyncProcessorIntegrationTest.java
- kafka-client/src/test/java/dev/responsive/kafka/testutils/SimpleStatefulProcessor.java
- kafka-client/src/test/java/dev/responsive/kafka/testutils/SimpleStatefulProcessorSupplier.java
- kafka-client/src/test/java/dev/responsive/kafka/testutils/SimpleStatelessProcessorSupplier.java
Adds support for using async with any number and type of processors in the same topology, and adds an integration test with multiple stateful and stateless async processors in one app.
> Support multiple/mixed async processors

- kafka-client/src/main/java/dev/responsive/kafka/internal/stores/PartitionedOperations.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/stores/SegmentedOperations.java
This patch cleans up the commit buffer and store registration if a store's operations provider fails to initialize. If we don't clean this up, we leave around stuff like metrics and stale registrations, which can cause downstream errors like failure to register store metrics.
> clean up the commitbuffer and store registration if store init fails

- kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/e2etest/E2ETestDriver.java
Use details obj to specify details for unreachable asserts. This will reduce the error spam we get because Antithesis groups failures according to the error msg.
> use details obj to specify details for unreachable asserts

- kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
- kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncProcessor.java
- kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncThreadPool.java
- kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncUtils.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/db/partitioning/Segmenter.java
- responsive-test-utils/src/main/java/dev/responsive/kafka/api/ResponsiveTopologyTestDriver.java
- responsive-test-utils/src/main/java/dev/responsive/kafka/internal/clients/TTDCassandraClient.java
- responsive-test-utils/src/main/java/dev/responsive/kafka/internal/db/TTDWindowTable.java
- responsive-test-utils/src/main/java/dev/responsive/kafka/internal/stores/WindowStoreStub.java
- responsive-test-utils/src/main/java/org/apache/kafka/streams/TTDUtils.java
- responsive-test-utils/src/test/java/dev/responsive/kafka/api/ResponsiveTopologyTestDriverKeyValueStoreTest.java
- responsive-test-utils/src/test/java/dev/responsive/kafka/api/ResponsiveTopologyTestDriverWindowStoreTest.java
Combination of #398 and #399  for the full fix
> Support async in Responsive TTD

- kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/common/UncaughtStreamsAntithesisHandler.java
Collection of several fixes to make finding and root-causing errors easier when they pop up in our Antithesis runs. Addresses some bugs and makes better use of the Antithesis SDK to log top-level info
Going to merge this so I have it available before I start mucking around with the Mongo test again
> Fix error handling, unwrapping, and logging in Antithesis

- kafka-client/src/test/java/dev/responsive/kafka/integration/ResponsiveWindowStoreIntegrationTest.java
There were a bunch of problems with the existing windowed integration test, not least annoying the one that latches always waited for the full timeout and didn't fail the test. This rewrite makes the tests much faster and more reliable.
> improve window integration test

- kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/Store.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/grpc/ApiCredential.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/grpc/GrpcRS3Client.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/grpc/PssStubsProvider.java
- kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/grpc/middleware/ApiKeyInterceptor.java
- expose the pss id list from Store
- support passing the internal api key to the auth interceptor
> changes to get rs3 healthcheck working
