responsivedev/responsive-pub

.github/workflows/github-main.yaml
.github/workflows/github-pr.yaml
.github/workflows/github-publish.yaml
buildSrc/src/main/kotlin/responsive.java-common-conventions.gradle.kts

Makes the following changes:
- renames the actions to be more descriptive
- publishes artifacts to S3 every main build
- runs the dry run release on the PR builder
- adds `versionIncrementer` configuration for the publish artifacts job and defaults to `incrementMinor`

clean up some of the GHA scripts

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/responsive.java-common-conventions.gradle.kts

Sample output:
```
> Task :kafka-client:test
dev.responsive.db.CassandraClientIntegrationTest
✔ shouldReturnAllKeysInLexicalOrder() (1.8s)
✔ shouldReturnRangeKeysInLexicalOrder() (1.2s)
dev.responsive.kafka.store.CommitBufferTest
✔ shouldIgnoreFlushFailuresOnRestore() (5.6s)
✔ shouldRestoreRecordsGreaterThanCassandraOffset() (4.6s)
✔ shouldThrowErrorOnFlushWhenSmallerOffset() (4.5s)
✔ shouldFlushAndUpdateOffsetWhenLargerOffset() (4.5s)
✔ shouldThrowErrorOnFlushWhenDifferentTxnIdIsSet() (4.5s)
✔ shouldDeleteRowInCassandraWithTombstone() (4.4s)
✔ shouldThrowErrorOnFlushWhenEqualOffset() (4.4s)
dev.responsive.kafka.store.LocalRemoteKvIteratorTest
✔ shouldIgnoreTombstoneWithNoRemoteMatch()
✔ shouldIgnoreRemoteValueWithLocalTombstone()
✔ shouldIterateLocalOnlyWithTombstones()
✔ …
```

add plugin for logging tests

---

operator/build.gradle.kts
operator/docker/scripts/run-operator
operator/src/main/java/dev/responsive/k8s/operator/OperatorMain.java
settings.gradle.kts

* Fix the imports to match the conventions with kotlin
* update the docker run script to include command line args
* set default values of the api key and secret configs to empty string. With this, and the server side code to make auth [optional](https://github.com/responsivedev/responsive-platform/pull/21), things should just work ™ in test environments.

Misc cleanups to the auth code

---

operator/docker/scripts/run-operator
operator/src/main/helm/templates/deployment.yaml
operator/src/main/java/dev/responsive/k8s/operator/OperatorMain.java
operator/src/main/java/dev/responsive/k8s/operator/OperatorOptions.java
operator/src/main/java/dev/responsive/k8s/operator/PropertiesLoader.java
operator/src/test/java/dev/responsive/k8s/operator/PropertiesLoaderTest.java
operator/src/test/resources/sample.properties
operator/src/test/resources/sample.properties.b64
settings.gradle.kts

Use `java.util.Properties` because it accepts a reader which can either read directly from a non-b64 encoded file or just load a `Reader` with the decoded contents.

use b64 encoded secrets file

---

operator/src/main/java/dev/responsive/k8s/controller/ControllerProtoFactories.java
operator/src/main/java/dev/responsive/k8s/crd/ResponsivePolicySpec.java
operator/src/main/java/dev/responsive/k8s/operator/reconciler/DemoPolicyPlugin.java
operator/src/main/java/dev/responsive/k8s/operator/reconciler/ResponsivePolicyReconciler.java

when migrating from JDK17->11 I used record style getters (no `getX` prefix) but this causes Jackson to fail as it expects getters with a specific naming convention. Instead of changing convention, I renamed the getters.

add getX prefix to Jackson getters

---

operator/src/main/java/dev/responsive/controller/client/grpc/ControllerGrpcClient.java
operator/src/test/java/dev/responsive/controller/client/grpc/ControllerGrpcClientTest.java

our controller endpoints are now secured we need this in order to establish the connection. will make it configurable so we can run test deployments later

use TLS for GRPC channel

---

operator/src/main/java/dev/responsive/k8s/controller/ControllerProtoFactories.java
operator/src/test/java/dev/responsive/k8s/controller/ControllerProtoFactoriesTest.java
operator/src/test/java/dev/responsive/k8s/operator/reconciler/ResponsivePolicyReconcilerTest.java

A policy that looks like:
```
apiVersion: "application.responsive.dev/v1"
kind: "ResponsivePolicy"
metadata:
name: example-policy
namespace: policies
spec:
applicationNamespace: responsive
applicationName: example
status: POLICY_STATUS_MANAGED
policyType: DEMO
demoPolicy:
maxReplicas: 2
```
should manage `responsive/example` not `policies/example-policy`

fix naming in policy spec

---

operator/src/main/helm/Chart.yaml
operator/src/main/helm/templates/appclusterrole.yaml
operator/src/main/helm/templates/appclusterrolebinding.yaml
operator/src/main/helm/templates/responsiveclusterrole.yaml
operator/src/main/helm/templates/responsiveclusterrolebinding.yaml

```bash
$ kubectl describe clusterrole -n responsive responsive-operator-app-role
Name:         responsive-operator-app-role
Labels:       app.kubernetes.io/managed-by=Helm
app.kubernetes.io/version=27e9457
helm.sh/chart=responsive-operator-0.1.0
Annotations:  meta.helm.sh/release-name: responsive-operator
meta.helm.sh/release-namespace: responsive
PolicyRule:
Resources          Non-Resource URLs  Resource Names  Verbs
---------          -----------------  --------------  -----
deployments.apps   []                 []              [get list patch update watch]
replicasets.apps   []                 []              [get list patch update watch]
statefulsets.apps  []                 []              [get list patch update watch]
$ kubectl describe clusterrole -n responsive …
```

fix helm chart role bindings

---

kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveDriver.java
kafka-client/src/main/java/dev/responsive/kafka/api/StreamsStoreDriver.java
responsive-test-utils/build.gradle.kts
responsive-test-utils/src/main/java/dev/responsive/kafka/api/TestStoreDriver.java
responsive-test-utils/src/test/java/dev/responsive/kafka/api/TopologyTestDriverExampleTest.java
responsive-test-utils/src/test/resources/log4j.properties
settings.gradle.kts

This makes it possible to use `TestStoreDriver` with `TopologyTestDriver` and abstracts away an interface for the `ResponsiveDriver`.

add responsive-test-utils module and refactor Driver

---

kafka-instrumentation/src/main/java/dev/responsive/kafka/clients/EndOffsetsPoller.java
kafka-instrumentation/src/main/java/dev/responsive/kafka/clients/MetricPublishingCommitListener.java
kafka-instrumentation/src/test/java/dev/responsive/kafka/clients/EndOffsetsPollerTest.java
kafka-instrumentation/src/test/java/dev/responsive/kafka/clients/MetricPublishingCommitListenerTest.java

EndOffsetsPoller: listens for partitions assigned/revoked, polls the end offsets
for the assigned partitions, and publishes the offset as a metric.
MetricsPublishingCommitListener: listens for partitions assigned/revoked and for
committed offsets, and publishes the current commmitted offset for all assigned
partitions.
~Just opening a mock PR to facilitate review of https://github.com/responsivedev/responsive-pub/pull/33~
~This shows [PR #33](https://github.com/responsivedev/responsive-pub/pull/33) relative to [PR #32](https://github.com/responsivedev/responsive-pub/pull/32)~

add consumer/producer listeners that publish metrics

---

operator/build.gradle.kts
operator/docker/Dockerfile
operator/docker/scripts/log4j-console-only.yaml
operator/docker/scripts/log4j-with-kafka.yaml
operator/docker/scripts/run-operator
operator/src/main/helm/templates/deployment.yaml
operator/src/main/helm/values.yaml
operator/src/main/java/dev/responsive/k8s/operator/OperatorMain.java
operator/src/main/java/dev/responsive/kafka/auth/PropertiesFileLoginModule.java
settings.gradle.kts

This patch sets operator deployments up to log to our logging pipeline:
- packages operator with log4j2, which ships with a maintained kafka appender
- adds a customized login module for authenticating with ccloud brokers. It reads username/password from a separate file (rather than the log4j properties file). This way we can put the api key/secret in a k8s secret.
- docker run script sets up a log4j properties file that logs to kafka, if configured to do so.
- helm chart mounts kafka secret and sets up environment variables so that log4j with kafka can be used.
Tested using local operator in kind running against a real observability stack"

log operator logs to our logging pipeline

---

buildSrc/src/main/kotlin/responsive.java-common-conventions.gradle.kts
settings.gradle.kts
tools/README.md
tools/build.gradle.kts
tools/src/main/java/dev/responsive/tools/StreamsBytecodeAnalyzer.java
tools/src/main/java/dev/responsive/tools/Visitors.java

copy-pasting the README.md - for now there's only one tool so I didn't bother including a CLI options parser
This module contains tools that can be helpful when using the Responsive
Platform. To run a tool in this module execute:
```bash
./gradlew :tools:run --args=<args>
```
This tool accepts a JAR file path as its input and outputs all the methods
in the `org.apache.kafka.streams` package that the JAR references. An example
output:
```
> Task :tools:run
org/apache/kafka/streams/StreamsConfig -> [<init>(Map)]
org/apache/kafka/streams/kstream/KStream -> [selectKey(KeyValueMapper), to(String), join(KTable, ValueJoiner), filter(Predicate)]
org/apache/kafka/streams/KafkaStreams -> [<init>(Topology, StreamsConfig), start(), close()]
org/apache/kafka/streams/StreamsBuilder -> [table(String, …
```

add tools module + analyzer tool

---

kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveGlobalKeyValueBytesStoreSupplier.java
kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKeyValueBytesStoreSupplier.java
kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveWindowedStoreSupplier.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveGlobalStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveWindowStore.java
kafka-client/src/main/java/dev/responsive/utils/TableName.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsiveStoreEosIntegrationTest.java
kafka-client/src/test/java/dev/responsive/utils/TableNameTest.java

this PR will replace all characters that are passed in as the store name that are invalid in cassandra with `_`. it also removes the `"` (cc @ableegoldman 😆) and just deals with case insensitivity (which I think was the reason for adding them in first place).

support more store names

---

kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveDriver.java
kafka-client/src/main/java/dev/responsive/kafka/api/StreamsStoreDriver.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveStoreBuilder.java
responsive-test-utils/src/main/java/dev/responsive/kafka/api/TestStoreDriver.java

Just the timestamped key-value StoreBuilder which sets the cleanup policy to `[delete]` and makes sure this doesn't get overridden accidentally afterwards

Add timestampedKeyValueStoreBuilder to API

---

kafka-client/src/main/java/dev/responsive/kafka/clients/ResponsiveGlobalConsumer.java

Minor thing I missed before -- if we create a new admin with the client supplier just to be passed in to the global consumer, we need to make sure that admin client also gets closed.

Make sure the Admin client supplied to each global consumer is closed

---

kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveWindowStore.java

the on commit callback is only called when we flush anyway, so this ultimately caused us to call the `CommitBuffer#flush` method twice back to back leading to confusing statements cluttering the log (empty buffers)

dont use OnCommitCallback

---

kafka-client/src/main/java/dev/responsive/kafka/api/InternalConfigs.java
kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/main/java/dev/responsive/kafka/clients/ResponsiveKafkaClientSupplier.java
kafka-client/src/main/java/dev/responsive/kafka/clients/SharedClients.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveStoreRegistration.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveStoreRegistry.java
kafka-client/src/test/java/dev/responsive/kafka/clients/ResponsiveKafkaClientSupplierTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsiveStoreRegistryTest.java
responsive-test-utils/src/main/java/dev/responsive/kafka/api/ResponsiveTopologyTestDriver.java

This patch adds a collection of all created Responsive state stores called ResponsiveStoreRegistry. The collection is updated as stores are created and deleted, and is shared amongst various components - like the stores ad the client supplier - via an intenral config.

add responsive store registry

---

kafka-client/src/main/java/dev/responsive/kafka/api/CassandraClientFactory.java
kafka-client/src/main/java/dev/responsive/kafka/api/DefaultCassandraClientFactory.java
kafka-client/src/main/java/dev/responsive/kafka/api/InternalConfigs.java
kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/main/java/dev/responsive/kafka/clients/ResponsiveKafkaClientSupplier.java
kafka-client/src/main/java/dev/responsive/kafka/clients/ResponsiveRestoreConsumer.java
kafka-client/src/main/java/dev/responsive/kafka/store/CommitBuffer.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveGlobalStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveWindowStore.java
kafka-client/src/main/java/dev/responsive/utils/StoreUtil.java
kafka-client/src/test/java/dev/responsive/kafka/clients/ResponsiveRestoreConsumerTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/CommitBufferTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsiveStoreEosIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsiveStoreRegistryTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsiveStoreRestoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/utils/IntegrationTestUtils.java
kafka-client/src/test/java/dev/responsive/utils/StoreUtilTest.java
responsive-test-utils/src/main/java/dev/responsive/kafka/api/ResponsiveTopologyTestDriver.java

optimize restore and support compacted changelogs
- When restoring, fetch the last committed offset from the remote
store, and restore starting from that offset.
- Only truncate the changelog is the changelog topic is not a
topology source, and is not compacted.

optimize restore and support compacted changelogs

---

kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveGlobalStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsivePartitionedStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveStore.java
kafka-client/src/test/java/dev/responsive/kafka/store/CommitBufferTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsiveGlobalStoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsivePartitionedStoreEosIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsivePartitionedStoreRestoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsiveStoreTest.java
kafka-client/src/test/java/dev/responsive/utils/ContainerExtension.java
kafka-client/src/test/java/dev/responsive/utils/IntegrationTestUtils.java
kafka-client/src/test/java/dev/responsive/utils/ResponsiveConfigParam.java

`ResponsiveStore` is now just a wrapper that delegates to either `ResponsivePartitionedStore` or `ResponsiveGlobalStore` depending on the context passed in during initialization.
This allows us to remove the `globalX` methods in our API and match the existing streams apis.

use context to implicitly create global stores

---

kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/main/java/dev/responsive/kafka/clients/MetricPublishingCommitListener.java
kafka-client/src/main/java/dev/responsive/kafka/clients/OffsetRecorder.java
kafka-client/src/main/java/dev/responsive/kafka/clients/ResponsiveConsumer.java
kafka-client/src/main/java/dev/responsive/kafka/clients/ResponsiveKafkaClientSupplier.java
kafka-client/src/main/java/dev/responsive/kafka/clients/ResponsiveProducer.java
kafka-client/src/main/java/dev/responsive/kafka/clients/StoreCommitListener.java
kafka-client/src/main/java/dev/responsive/kafka/config/ResponsiveDriverConfig.java
kafka-client/src/main/java/dev/responsive/kafka/store/CommitBuffer.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsivePartitionedStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveStoreRegistration.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveWindowStore.java
kafka-client/src/test/java/dev/responsive/kafka/clients/MetricPublishingCommitListenerTest.java
kafka-client/src/test/java/dev/responsive/kafka/clients/OffsetRecorderTest.java
kafka-client/src/test/java/dev/responsive/kafka/clients/ResponsiveConsumerTest.java
kafka-client/src/test/java/dev/responsive/kafka/clients/ResponsiveKafkaClientSupplierTest.java
kafka-client/src/test/java/dev/responsive/kafka/clients/ResponsiveProducerTest.java
kafka-client/src/test/java/dev/responsive/kafka/clients/StoreCommitListenerTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/CommitBufferTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsiveGlobalStoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsivePartitionedStoreEosIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsivePartitionedStoreRestoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsiveStoreRegistryTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsiveStoreTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsiveWindowIntegrationTest.java
kafka-client/src/test/java/dev/responsive/utils/IntegrationTestUtils.java

This patch flushes state stores on every streams commit. The stores discover commits and the associated offsets via a notification registered with ResponsiveStoreRegistry. The notification is called by a ResponsiveProducer callback on each commit

flush state stores on every commit

---

kafka-client/src/main/java/dev/responsive/kafka/store/CommitBuffer.java
kafka-client/src/test/java/dev/responsive/kafka/store/CommitBufferTest.java

- Break up received restore batches into batches that use the Cassandra max batch size. Otherwise, the atomic writer will break them up, but will use the offset for the entire received batch as the fencing offset for all the batches - which will cause the subsequent batches to fail (as the protocol expects that once the fencing offset is set, all data up to that offset has been written).
- Make the maximum batch size parameterizable. My local test was timing out with the default of 1000. -

break up restore batches in to chunks of the maximum batch size

---

kafka-client/src/main/java/dev/responsive/db/CassandraClient.java
kafka-client/src/main/java/dev/responsive/kafka/api/CassandraClientFactory.java
kafka-client/src/main/java/dev/responsive/kafka/api/DefaultCassandraClientFactory.java
kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/main/java/dev/responsive/kafka/config/ResponsiveConfig.java
kafka-client/src/main/java/dev/responsive/kafka/store/AtomicWriter.java
kafka-client/src/main/java/dev/responsive/kafka/store/BufferPlugin.java
kafka-client/src/main/java/dev/responsive/kafka/store/CommitBuffer.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsivePartitionedStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveWindowStore.java
kafka-client/src/main/java/dev/responsive/utils/SubPartitioner.java
kafka-client/src/test/java/dev/responsive/kafka/store/AtomicWriterTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/CommitBufferDrainTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/CommitBufferTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsivePartitionedStoreRestoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsiveStoreTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsiveWindowIntegrationTest.java
kafka-client/src/test/java/dev/responsive/utils/ContainerExtension.java
kafka-client/src/test/java/dev/responsive/utils/SubPartitionerTest.java
kafka-client/src/test/resources/junit-platform.properties

Review guide:
1. Rename `ResponsiveDriverConfig` to `ResponsiveConfig` since we no longer have a `ResponsiveDriver` class
2. Introduce `SubPartitioner` that has the sub-partitioning algorithm
3. Make changes to `CommitBuffer` to support subpartitions
4. Tests for the above
This PR doesn't make any functional changes since it is hardcodes everything to `SubPartitioner.NO_SUBPARTITIONS`. The next PR will wire through and add more E2E testing.

support subpartitioning (without wiring it in yet)

---

kafka-client/src/main/java/dev/responsive/kafka/config/ResponsiveConfig.java
kafka-client/src/main/java/dev/responsive/kafka/store/CommitBuffer.java
kafka-client/src/main/java/dev/responsive/kafka/store/FlushTriggers.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsivePartitionedStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveWindowStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/SizeTrackingBuffer.java
kafka-client/src/test/java/dev/responsive/kafka/store/CommitBufferTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsivePartitionedStoreRestoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsiveWindowIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/SizeTrackingBufferTest.java

Adds some more local (per-state-store) flush triggers:
- size-based: triggers flushes when the accumulated state is over some size in bytes
- time-based: triggers flushes when some number of milliseconds has elapsed since the last flush
Renames the existing config so the config names are consistent
Changes the default to flush every 30 seconds

add local flush triggers

---

kafka-client/src/main/java/dev/responsive/db/CassandraClient.java
kafka-client/src/main/java/dev/responsive/kafka/store/AtomicWriter.java
kafka-client/src/main/java/dev/responsive/kafka/store/CommitBuffer.java
kafka-client/src/test/java/dev/responsive/kafka/store/CommitBufferTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsivePartitionedStoreRestoreIntegrationTest.java

follow up from #70 
Doesn't seem to affect the max process rate (expected) but the max commit time ms definitely has a stat-sig drop, which I think will reduce load on C*:

only write offset to base subpartition

---

controller-api/src/main/proto/responsive/controller/internal/v1/controller.proto
controller-api/src/main/proto/responsive/controller/v1/controller.proto
operator/src/main/java/dev/responsive/k8s/controller/ControllerProtoFactories.java
operator/src/main/java/dev/responsive/k8s/controller/DemoPolicyProtoFactories.java
operator/src/main/java/dev/responsive/k8s/crd/CrdUtils.java
operator/src/main/java/dev/responsive/k8s/crd/DemoPolicy.java
operator/src/main/java/dev/responsive/k8s/crd/ResponsivePolicySpec.java
operator/src/main/java/dev/responsive/k8s/crd/ResponsivePolicyStatus.java
operator/src/main/java/dev/responsive/k8s/operator/reconciler/ResponsivePolicyReconciler.java
operator/src/test/java/dev/responsive/k8s/controller/ControllerProtoFactoriesTest.java
operator/src/test/java/dev/responsive/k8s/crd/ResponsivePolicySpecTest.java
operator/src/test/java/dev/responsive/k8s/operator/reconciler/DemoPolicyPluginTest.java
operator/src/test/java/dev/responsive/k8s/operator/reconciler/ResponsivePolicyReconcilerTest.java

- Extend the policy CRD to support a configurable list of diagnosers, and add specs for rate-based diagnosers that can scale up or down based on processing rate per node.
- Clean up the validation logic in the CRDs. No validation happens in the consturctor, as exceptions there cause operator to crash. Instead the reconciler validates and marks the policy as failed if the speci s bad

extend policy spec to support rate-based diagnosers

---

operator/src/main/helm/templates/deployment.yaml
operator/src/main/helm/values.yaml
operator/src/main/java/dev/responsive/k8s/controller/ControllerProtoFactories.java
operator/src/main/java/dev/responsive/k8s/operator/OperatorMain.java
operator/src/main/java/dev/responsive/k8s/operator/OperatorOptions.java
operator/src/main/java/dev/responsive/k8s/operator/reconciler/DemoPolicyPlugin.java
operator/src/main/java/dev/responsive/k8s/operator/reconciler/ResponsivePolicyReconciler.java
operator/src/test/java/dev/responsive/k8s/controller/ControllerProtoFactoriesTest.java
operator/src/test/java/dev/responsive/k8s/operator/reconciler/DemoPolicyPluginTest.java
operator/src/test/java/dev/responsive/k8s/operator/reconciler/ResponsivePolicyReconcilerTest.java

Adds a command line option --environment to set an environment
prefix in calls to the controller. This can be used to distinguish applications
in different k8s clusters (or other grouping of the user's choice). Also
adds support to the helm chart for specifying options.

allow setting an environment prefix in operator

---

.github/workflows/github-main.yaml
.github/workflows/github-publish.yaml
buildSrc/src/main/kotlin/responsive.java-common-conventions.gradle.kts

With this patch, suppose the last released version of kafka-clients is 0.4.0. Then, all master builds will build kafka-clients with 0.5.0-SNAPSHOT. The next publish job will release 0.5.0, and then master will build 0.6.0-SNAPSHOT.
After this patch, I will manually run the following to get everything on the "right" snapshot version.:
```
./gradlew markNextVersion -Prelease.dryRun | grep Creating | commit --allow-empty -F -
git push
./gradlew markNextVersion
```

setup the build and workflows to use snapshot versioning.

---

.github/workflows/github-main.yaml
.github/workflows/github-pr.yaml
kafka-client-examples/simple-example/build.gradle.kts
kafka-client-examples/simple-example/docker/Dockerfile
kafka-client-examples/simple-example/docker/scripts/otel-jmx.config
kafka-client-examples/simple-example/docker/scripts/run-simpleapp
kafka-client-examples/simple-example/src/main/java/dev/responsive/examples/simpleapp/Main.java
kafka-client-examples/simple-example/src/main/java/dev/responsive/examples/simpleapp/SimpleApplication.java
settings.gradle.kts

Adds the smoke test app from sindri to the public repo
under a new module kafka-client-examples::simple-example.
Adds steps to the PR builder to run smoke tests

Add system test app

---

.github/workflows/github-publish.yaml
.gitignore

Update publish GHA workflow to run smoke tests and promote images. I tested this
in my own fork of this repo to avoid messing with the release tags here.

Update publish GHA workflow to run smoke tests and promote images

---

.github/workflows/github-main.yaml
.github/workflows/github-publish.yaml
buildSrc/src/main/kotlin/responsive.docker.gradle.kts
operator/docker/Dockerfile

- Add a pushDockerMultiArch task that builds and pushes a multi-architecture docker image.
- Update the github workflows to support using the new task. Each workflow that pushes images now needs extra steps to fetch the qemu emulator and install the docker build extensions.

builds docker images for amd64 and aarch64/arm64

---

kafka-client/src/main/java/dev/responsive/db/CassandraClient.java
kafka-client/src/main/java/dev/responsive/db/CassandraFactSchema.java
kafka-client/src/main/java/dev/responsive/db/CassandraKeyValueSchema.java
kafka-client/src/main/java/dev/responsive/db/CassandraWindowedSchema.java
kafka-client/src/main/java/dev/responsive/db/ColumnName.java
kafka-client/src/main/java/dev/responsive/db/LwtFencingToken.java
kafka-client/src/main/java/dev/responsive/db/RowType.java
kafka-client/src/test/java/dev/responsive/db/KeyValueSchemaIntegrationTest.java

depends on #91 - adds a row type byte to each data key so that we can differentiate between a metadata key and a data key with the same byte contents

support data keys that are equal to the metadata key literal

---

config/checkstyle/checkstyle.xml
kafka-client/src/main/java/dev/responsive/db/CassandraFactSchema.java
kafka-client/src/main/java/dev/responsive/db/CassandraKeyValueSchema.java
kafka-client/src/main/java/dev/responsive/db/CassandraWindowedSchema.java
kafka-client/src/main/java/dev/responsive/db/LwtWriterFactory.java
kafka-client/src/main/java/dev/responsive/db/RemoteSchema.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsivePartitionedStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveWindowStore.java
responsive-test-utils/build.gradle.kts
responsive-test-utils/src/main/java/dev/responsive/kafka/api/CassandraClientStub.java
responsive-test-utils/src/main/java/dev/responsive/kafka/api/KVStoreStub.java
responsive-test-utils/src/main/java/dev/responsive/kafka/api/ResponsiveTopologyTestDriver.java
responsive-test-utils/src/main/java/dev/responsive/kafka/api/TTDKeyValueSchema.java
responsive-test-utils/src/main/java/dev/responsive/kafka/api/TTDSchema.java
responsive-test-utils/src/main/java/dev/responsive/kafka/api/TTDWindowedSchema.java
responsive-test-utils/src/main/java/dev/responsive/kafka/api/WindowStoreStub.java
responsive-test-utils/src/test/java/dev/responsive/kafka/api/TopologyTestDriverExampleTest.java

Fills out the TopologyTestDriver ecosystem of stubbed clients, schemas, writers, and stores with a basic in-memory map for use in a TTD test app

Finish Responsive TTD with stubbed clients and store schemas

---

kafka-client/src/main/java/dev/responsive/db/CassandraFactSchema.java
kafka-client/src/main/java/dev/responsive/db/CassandraKeyValueSchema.java
kafka-client/src/main/java/dev/responsive/db/CassandraWindowedSchema.java
kafka-client/src/main/java/dev/responsive/db/RemoteSchema.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveGlobalStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsivePartitionedStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveWindowStore.java
kafka-client/src/test/java/dev/responsive/db/CassandraFactSchemaIntegrationTest.java
kafka-client/src/test/java/dev/responsive/db/KeyValueSchemaIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/CommitBufferTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsivePartitionedStoreEosIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsivePartitionedStoreRestoreIntegrationTest.java
responsive-test-utils/src/main/java/dev/responsive/kafka/store/TTDKeyValueSchema.java
responsive-test-utils/src/main/java/dev/responsive/kafka/store/TTDWindowedSchema.java

TWCS doesn't perform well if there are rows that are replaced. This assumption was not respected with the metadata (offset) rows, that were replaced regularly potentially messing up compaction.
The only meaningful change is in `kafka-client/src/main/java/dev/responsive/db/CassandraFactSchema.java`

Separate metadata into its own table for Fact Tables

---

.github/workflows/github-pr.yaml

Use a locally built operator in smoke tests. This ensures we test the operator from PR
builds.
Logs in to ECR public for PR builds. We do this because authenticated image pulls
have a much higher rate-limit, so we avoid failing smoke tests on pulling the image.
Note that this change is defensive. Currently we don't pull from ECR public in PR builds.

login to ecr public and use a locally build operator for smoke tests in PRs

---

kafka-client/src/main/java/dev/responsive/db/CassandraFactSchema.java
kafka-client/src/main/java/dev/responsive/db/CassandraKeyValueSchema.java
kafka-client/src/main/java/dev/responsive/db/CassandraWindowedSchema.java
kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveStores.java
kafka-client/src/main/java/dev/responsive/kafka/clients/DelegatingConsumer.java
kafka-client/src/main/java/dev/responsive/kafka/clients/ResponsiveConsumer.java
kafka-client/src/main/java/dev/responsive/kafka/clients/ResponsiveGlobalConsumer.java
kafka-client/src/main/java/dev/responsive/kafka/clients/ResponsiveKafkaClientSupplier.java
kafka-client/src/main/java/dev/responsive/kafka/clients/ResponsiveRestoreConsumer.java
kafka-client/src/main/java/dev/responsive/kafka/clients/StoreCommitListener.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveGlobalStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveStoreRegistration.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveStoreRegistry.java
kafka-client/src/test/java/dev/responsive/kafka/clients/ResponsiveConsumerTest.java
kafka-client/src/test/java/dev/responsive/kafka/clients/ResponsiveRestoreConsumerTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsiveStoreTest.java
responsive-test-utils/src/main/java/dev/responsive/kafka/store/CassandraClientStub.java

Main change here is a fix in the ResponsiveRestoreConsumer, to avoid accidentally resetting any actively restoring changelogs back to their starting offset when new restoring tasks are added.
Cleaned up a few miscellaneous things I happened to notice in the various kafka clients on the side.
Also includes a few related (but minor) refactors from https://github.com/responsivedev/responsive-pub/pull/97/ to help break that up

fix: initialize restore consumer offsets once

---

kafka-client/src/main/java/dev/responsive/db/CassandraFactSchema.java
kafka-client/src/main/java/dev/responsive/db/CassandraKeyValueSchema.java
kafka-client/src/main/java/dev/responsive/db/CassandraWindowedSchema.java
kafka-client/src/main/java/dev/responsive/db/ColumnName.java
kafka-client/src/main/java/dev/responsive/db/FactSchemaWriter.java
kafka-client/src/main/java/dev/responsive/db/LwtWriter.java
kafka-client/src/main/java/dev/responsive/db/RemoteKeyValueSchema.java
kafka-client/src/main/java/dev/responsive/db/RemoteSchema.java
kafka-client/src/main/java/dev/responsive/db/RemoteWriter.java
kafka-client/src/main/java/dev/responsive/kafka/store/CommitBuffer.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveGlobalStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsivePartitionedStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveWindowStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/SizeTrackingBuffer.java
kafka-client/src/main/java/dev/responsive/model/Result.java
kafka-client/src/main/java/dev/responsive/utils/Iterators.java
kafka-client/src/test/java/dev/responsive/db/CassandraFactSchemaIntegrationTest.java
kafka-client/src/test/java/dev/responsive/db/KeyValueSchemaIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/CommitBufferTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/FactSchemaWriterTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/LocalRemoteKvIteratorTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/LwtWriterTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/SizeTrackingBufferTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/SubPartitionIntegrationTest.java
kafka-client/src/test/java/dev/responsive/model/ResultTest.java
responsive-test-utils/src/main/java/dev/responsive/kafka/store/TTDKeyValueSchema.java
responsive-test-utils/src/main/java/dev/responsive/kafka/store/TTDSchema.java
responsive-test-utils/src/main/java/dev/responsive/kafka/store/TTDWindowedSchema.java

this PR changes the table schema to include a `TIMESTAMP` clustering column so that we can semantically respect the TTL based on event time even if wall clock TTL hasn't kicked in.

respect TTL semantically even if data is not physically cleared

---

controller-api/src/main/proto/responsive/controller/v1/controller.proto
operator/src/main/java/dev/responsive/k8s/controller/DemoPolicyProtoFactories.java
operator/src/main/java/dev/responsive/k8s/controller/DiagnoserProtoFactories.java
operator/src/main/java/dev/responsive/k8s/crd/kafkastreams/DiagnoserSpec.java
operator/src/main/java/dev/responsive/k8s/crd/kafkastreams/FixedReplicaScaleUpStrategySpec.java
operator/src/main/java/dev/responsive/k8s/crd/kafkastreams/MeanSojournTimeDiagnoserSpec.java
operator/src/main/java/dev/responsive/k8s/crd/kafkastreams/ScaleUpStrategySpec.java
operator/src/test/java/dev/responsive/k8s/controller/ControllerProtoFactoriesTest.java
operator/src/test/java/dev/responsive/k8s/crd/ResponsivePolicySpecTest.java

add models for mean sojourn time and saturation diagnosers
mean sojourn time diagnoser: this diagnoser takes a target for "mean sojourn time"
and will try to make sure the application can satisfy this target. The mean
sojourn time is the time expected to process a record appended to a source
topic partition.
saturation diagnoser: this diagnoser attemmpts to keep thread "saturation" over
some target. Saturation is the percentage of time a given thread spends not in poll
(e.g. processing data). A low value means the thread is idle.

add controller models for new policies

---

kafka-client-examples/simple-example/src/main/java/dev/responsive/examples/simpleapp/SimpleApplication.java

Bumps the timeout for the smoke test app. Currently our smoke tests
occasionally fail with:
```
"2023-08-31T16:24:14.542Z",,"""responsive-platform-sindriLocal-system-test-platform-add-the-mean-sojourn-time-diagnoser""","Exception in thread ""main"" com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S"
```
The default of 2 seconds seems short. This patch bumps the timeout to 10 seconds.

bump the test app keyspace create timeout

---

kafka-client/src/main/java/dev/responsive/db/CassandraWindowedSchema.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsivePartitionedStore.java
kafka-client/src/main/java/dev/responsive/kafka/store/ResponsiveWindowStore.java

Both KV and Window stores allow deletion via put with a null value in Kafka Streams. We need to handle these properly as tombstones and enable deletes for window stores

Support null-value deletes 

---

responsive-test-utils/src/main/java/dev/responsive/kafka/api/ResponsiveTopologyTestDriver.java
responsive-test-utils/src/main/java/dev/responsive/kafka/clients/TTDCassandraClient.java
responsive-test-utils/src/main/java/dev/responsive/kafka/clients/TTDMockAdmin.java
responsive-test-utils/src/main/java/dev/responsive/kafka/store/TTDKeyValueSchema.java
responsive-test-utils/src/main/java/dev/responsive/kafka/store/TTDSchema.java
responsive-test-utils/src/main/java/dev/responsive/kafka/store/TTDWindowedSchema.java
responsive-test-utils/src/main/java/org/apache/kafka/streams/TTDUtils.java
responsive-test-utils/src/test/java/dev/responsive/kafka/api/ResponsiveTopologyTestDriverTest.java

The main fix here is in how we "create" topics within the MockAdmin used by the RTTD. Because no real topics are created in the TTD context, everything has to mock its own internal view of the "cluster" which in the admin case, means making sure that it adds any topics that we will later make requests for. For us, this is just changelogs (and should generally only ever be changelogs, as the input topics are completely abstracted away by the TTD entirely including everything like the KafkaClientSupplier)
Before this, we would lazily create topics when requested for in the #describeTopics API. However for FACT tables we skip this particular call, and so incur an error when we next hit the mock admin in the #describeConfigs call.
The fix is to remove any topic-creation inside Admin overrides …

fix: initialize TTDMockAdmin with the changelogs to create up front

---

kafka-client-examples/simple-example/src/main/java/dev/responsive/examples/simpleapp/SimpleApplication.java
kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/test/java/dev/responsive/kafka/api/ResponsivePartitionedStoreRestoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsiveGlobalStoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsivePartitionedStoreEosIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/ResponsiveWindowIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/store/SubPartitionIntegrationTest.java

This PR changes the way applications are created from the somewhat awkward static `ResponsiveKafkaStreams.connect` constructors, to something that is fully analogous with vanilla KafkaStreams basic constructors (and thus easily migrated via find-and-replace).
It was a huge hassle and takes a really long sequence of constructors with iterative parameters, but it was worth it I think.
I did leave in the one static constructor that I believe is currently being used, and will remove it in a separate PR I have planned with other changes that will break our current user's code and need to be updated, so we can do that when everyone is ready

Convert to pure ResponsiveKafkaStreams constructor setup

---

kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/main/java/dev/responsive/kafka/clients/config/ResponsiveStreamsConfig.java
kafka-client/src/main/java/dev/responsive/kafka/config/ResponsiveConfig.java
kafka-client/src/main/java/dev/responsive/utils/StoreUtil.java
kafka-client/src/test/java/dev/responsive/kafka/api/ResponsivePartitionedStoreRestoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/clients/config/ResponsiveStreamsConfigTest.java
kafka-client/src/test/java/dev/responsive/utils/StoreUtilTest.java
responsive-test-utils/src/main/java/dev/responsive/kafka/api/ResponsiveTopologyTestDriver.java

Get this ready to publish the API Reference docs. Fills in a few niche missing constructors (KafkaStreams allows you to pass in a `Time` object), adds javadocs for everything, and cleans up the way we handle StreamsConfigs and validate the properties.
Introduces a new ResponsiveStreamsConfig class so we can do "quiet logging". Will follow up with the same for the other kafka clients that we're excessively logging

Finalize ResponsiveKafkaStreams API and clean up StreamsConfig

---

.github/actions/for-module-in-group/action.yaml
.github/actions/gradle-build-and-publish/action.yaml

Although the actual artifacts are already being released with the same version across a module group, since we're forcing the version of the sub-module in the build to align with the root module's version, we need to make sure the submodule's axion release version (ie basically just the tags in the repo) is also aligned with the root module.
This should fix the publishing workflow which was broken due to issues with the axion release and version/tag collisions

Align axion release versions within module group

---

kafka-client/src/main/java/dev/responsive/kafka/clients/EndOffsetsPoller.java
kafka-client/src/main/java/dev/responsive/kafka/clients/ResponsiveKafkaClientSupplier.java

Noticed a flood of INFO-level logging in the soak, mainly about updating the end offsets which is done every 30s but per-partition. Can definitely be reduced to a single line, and possibly bumped down to DEBUG

Clean up EndOffsetsPoller logging

---

kafka-client/src/main/java/dev/responsive/internal/config/ResponsiveStreamsConfig.java
kafka-client/src/main/java/dev/responsive/internal/stores/CommitBuffer.java
kafka-client/src/test/java/dev/responsive/internal/config/ResponsiveStreamsConfigTest.java
kafka-client/src/test/java/dev/responsive/internal/stores/CommitBufferTest.java

We should now be able to handle all topology optimizations, specifically reusing source topics as changelogs which is currently a restricted config.
We can simply remove all validation of the `topology.optimization` config, though we do want to be guard against users accidentally deleting source topic data and therefore should make sure to disable changelog truncation for any source tables with this source-changelog optimization

Allow all topology optimizations and disable truncation for source-topic changelogs

---

kafka-client/src/main/java/dev/responsive/kafka/internal/stores/CommitBuffer.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsivePartitionedStore.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveWindowStore.java

Debugging the soak has been great practice for our logs and their usefulness vs sanity ratio. With the various offset pollers reduced in frequency, the CommitBuffer logging around flushes seems to be the most aggressive thing left, definitely too much for INFO
Tried to strike a good balance by bumping the high frequency logging to DEBUG with some new summary logging for us to have something at INFO.

Reduce INFO level logging of flushes by the CommitBuffer

---

kafka-client/build.gradle.kts
kafka-client/src/main/java/dev/responsive/kafka/api/config/ResponsiveConfig.java

Added a task to the gradle build that stashes some various useful git properties in a file along with the main build. We can then read this out to log valuable debugging info such as the version and specific commit id of the dependency.
Tested this out both in a local kafka-client integration test, and by pulling in a local build with the fix while running a test in the soak repo. Works with both, and logs for the TTD as well as real applications.
Useful for sanity checks, both in the soak test and future customer logs where we want to verify exactly what version they're running. I only put it in the kafka-client module since that's where it seems most relevant, but we could extend it to others as well if that feels right.

Log version and git commit id during startup

---

kafka-client/src/main/java/dev/responsive/kafka/internal/stores/CommitBuffer.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsivePartitionedStore.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveWindowStore.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/CommitBufferTest.java

Planning to step this up in the soak and have been pretty concerned about doing all these blocking requests on the relatively-hot-path of flushing. Since we don't depend on changelog truncation in any way and it's completely idempotent, retriable, etc we can just kick off a new deleteRecords request after each flush without waiting for it to complete. When the next flush comes around then we can check on the previous delete request's status and kick off a new request if it was succcessful, or else retry with the updated low-watermark offset to delete from
I hope this will help enough to call the feature production ready, but we should still be aware of admin calls and connections which have caused many issues with Streams in the past. If we still run into issues we could go a step further …

Make changelog truncation happen asynchronously by CommitBuffer

---

kafka-client/src/main/java/dev/responsive/kafka/internal/clients/ResponsiveGlobalConsumer.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraClient.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraFactSchema.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraGlobalKeyValueSchema.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraKeyValueSchema.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/FactSchemaWriter.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/LwtWriter.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/RemoteWriter.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveGlobalStore.java
kafka-client/src/test/java/dev/responsive/kafka/integration/ResponsiveGlobalStoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/integration/SubPartitionIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/ResponsiveStoreTest.java
responsive-test-utils/src/main/java/dev/responsive/kafka/internal/clients/TTDCassandraClient.java
responsive-test-utils/src/main/java/dev/responsive/kafka/internal/stores/TTDSchema.java

This PR does three things (let me know if you'd rather me split it up!):
1. It fixes an issue with time-travel where offsets are not committed after restoration but an `unsubscribe` is called, meaning those offsets get re-processed
2. It fixes a potential time-travel issue where restore reprocesses records during an unclean shutdown (essentially the same situation as above, but if a commit isn't called during normal processing) by persisting the last written offset to a metadata table
3. It improves the implementation to use Fact schema instead of the normal schema so we don't push everything into a single partition

fix and re-enable global stores

---

responsive-test-utils/build.gradle.kts

One-line change to how we declare one of the kafka related dependencies in the responsive client module group, specifically the responsive-test-utils module. We switch the `kafka-streams-test-utils` dependency from `implementation` to `api` so that it will be exported as part of the `responsive-test-utils` artifact, the same way we export the `kafka-streams` dependency with the `kafka-client` module
With this, users should be able to remove all explicit kafka dependencies from their maven/gradle build file and access everything through the responsive `kafka-client` and `responsive-test-utils`. Without this change, users will generally always need to explicitly pull in the `kafka-streams-test-utils` artifact to make use of the TopologyTestDriver features like …

Export all kafka-streams dependencies in Responsive api

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraClient.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraFactTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraKeyValueTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraWindowedTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/FactSchemaWriter.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/FactWriterFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/LwtWriter.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/LwtWriterFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/RemoteKVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/RemoteTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/RemoteWindowedTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/TableCache.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoKVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoWriter.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoWriterFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/ResponsiveMongoClient.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/CommitBuffer.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/GlobalOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/PartitionedOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveWindowStore.java
kafka-client/src/test/java/dev/responsive/kafka/integration/ResponsiveKeyValueStoreRestoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/integration/SubPartitionIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/CassandraFactTableIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/CassandraKVTableIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/CommitBufferTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/FactSchemaWriterTest.java
responsive-test-utils/src/main/java/dev/responsive/kafka/internal/clients/TTDCassandraClient.java
responsive-test-utils/src/main/java/dev/responsive/kafka/internal/stores/TTDKeyValueTable.java
responsive-test-utils/src/main/java/dev/responsive/kafka/internal/stores/TTDTable.java
responsive-test-utils/src/main/java/dev/responsive/kafka/internal/stores/TTDWindowedTable.java

Before this PR the `RemoteTable` API assumed Cassandra and therefore encoded `BoundStatement` in it. This sets the stage for returning something different for different backend implementations.

make the Table API generic to backend storage

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoKVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoWriter.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoWriterFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/ResponsiveMongoClient.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/CommitBuffer.java

Note that batches in mongo are _not_ atomic so it's possible that any number of writes within a batch will fail. That's OK because newer writers will succeed in overwriting anything with older epochs (not yet implemented, that's in the next PR that has EOS).
When I have Mongo fully implemented I'll add a suite of unit/integration tests.

[mongo] insert in bulk to avoid network roundtrips

---

etc/otel-jmx.config.yaml
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveKeyValueStore.java

Also fixes the metric names in the otel file after the flushes-fenced -> flush-errors change

Log a warning if standby tasks are created

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/FactWriterFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/LwtWriter.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/LwtWriterFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/WriterFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoWriterFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/CommitBuffer.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/FactSchemaWriterTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/LwtWriterTest.java
responsive-test-utils/src/main/java/dev/responsive/kafka/internal/stores/TTDTable.java

Relatively small refactor to clear up how batches are handled/sized between the CommitBuffer and RemoteWriters. It seems that the `batchSize` we pass in is always either the `MAX_BATCH_SIZE` constant or, in the case of restoration only, the size of the final batch that contains whatever records are remaining up to the `MAX_BATCH_SIZE`
In other words, the batch size is always capped at `MAX_BATCH_SIZE` and furthermore, the only time the `batchSize` parameter is different than the hard-coded constant is when there are fewer updates in the batch and thus the batch will be naturally capped at this smaller size since we will run out of inserts (or deletes) before hitting the `batchSize` condition. Also, only the lwt writer seems to be using this at the moment, so it feels silly for us to pass …

Remove batchSize parameter from writers

---

kafka-client/src/main/java/dev/responsive/kafka/api/config/ResponsiveConfig.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/StampedKeySpec.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/GlobalOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/KeyValueOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/PartitionedOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveKeyValueStore.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveWindowStore.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/SegmentedOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/WindowOperations.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/ResponsiveKeyValueStoreTest.java

Just a minor step in the window store implementation, most of the interesting stuff will be in the followup with the subpartitioner (which for now is just a TODO)
This PRs adds a WindowOperations interface with just the single SegmentedOperations implementation for now. Although there's only the one implementation of this, it's still nice to break up everything that's currently stuffed into the `ResponsiveWindowStore` implementation.
With this, all of the Streams/WindowStore semantics and logic stays in the ResponsiveWindowStore class while the actual storage engine/implementation details will go in the SegmentedOperations

Add WindowOperations and SegmentedOperations

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/KVDoc.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MetadataDoc.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoKVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoWriter.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoWriterFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/SessionUtil.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoKVTableTest.java

There are basically two changes:
1. pipe `epoch` through to where it's necessary
2. Changes in `MongoKVTable` to support EOS
You really only need to review the second to get a sense of whats' going on.
I tested it by running the EOS test against MongoDB, though I'll follow up this PR with a more significant testing suite for MongoDB stores in general.
MongoDB supports atomic updates on individual documents via the [findAndModify](https://www.mongodb.com/docs/manual/reference/method/db.collection.findAndModify/#std-label-findAndModify-upsert-example) upsert operation of the form:
```jsx
db.example.findAndModify({
query: { key: "0xDEADBEEF", epoch: { $lte: local_epoch } },
update: { $set: { key: "0xDEADBEEF", value: "0xCAFED00D", epoch: local_epoch } },
upsert: true
})
```
The `$lte: …

[mongo] eos support with epoch based fencing

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraKeyValueTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraWindowedTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/ColumnName.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/LwtWriterFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/partitioning/SegmentPartitioner.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/Stamped.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/StoreUtil.java
kafka-client/src/test/java/dev/responsive/kafka/integration/ResponsiveWindowStoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/CommitBufferTest.java

- The main change here is to start preserving the stream-time across restarts by persisting it in the metadata segment, along with the offset. 
- Also fixes some arithmetic/edge case errors in the SegmentPartitioner.
- With the above, we can re-enable the ResponsiveWindowStoreIntegrationTest

Persist stream-time for window stores

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/BytesKeySpec.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraTableSpecFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraWindowedTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/KeySpec.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/RemoteWindowedTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/StampedKeySpec.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/partitioning/SegmentPartitioner.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/CommitBuffer.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/LocalRemoteKvIterator.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/PartitionedOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveWindowStore.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/SegmentedOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/SizeTrackingBuffer.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/Iterators.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/MultiPartitionRangeIterator.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/Result.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/Stamped.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/LocalRemoteKvIteratorTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/SizeTrackingBufferTest.java
responsive-test-utils/src/main/java/dev/responsive/kafka/internal/db/TTDWindowedTable.java
responsive-test-utils/src/main/java/dev/responsive/kafka/internal/stores/WindowStoreStub.java

Main change here is to remove the generic <K> from the Stamped class and hard-code it to Bytes.
The rest of this PR is all the clean up that's enabled from this one change, mainly around removing generics from window store related iterators and from making the actual key generic <K> extend Comparable<K> instead of using the KeySpec class as a Comparator

Remove generic <K> from Stamped and clean up Comparator logic

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/StampedKeySpec.java

for some bizarre reason I had implemented this originally to read the ts from the key not the value, where it is actually stored. no idea how this ever passed any tests -- we should follow this up with comprehensive tests but I'm making this change to unblock the build.

fix stamped record deserializer

---

kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/main/java/dev/responsive/kafka/api/config/CompatibilityMode.java
kafka-client/src/main/java/dev/responsive/kafka/api/config/ResponsiveConfig.java
kafka-client/src/main/java/dev/responsive/kafka/internal/clients/ResponsiveKafkaClientSupplier.java
kafka-client/src/main/java/dev/responsive/kafka/internal/config/ConfigUtils.java
kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/EndOffsetsPoller.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/SessionClients.java
kafka-client/src/test/java/dev/responsive/kafka/api/ResponsiveKafkaStreamsTest.java
kafka-client/src/test/java/dev/responsive/kafka/integration/MinimalIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/clients/ResponsiveKafkaClientSupplierTest.java

the new config (`responsive.compatibility.mode = METRICS_ONLY`) effectively disables the following:
- config validation
- responsive restore consumer
- responsive global consumer
- connecting to responsive storage

support metrics-only mode in ResponsiveKafkaStreams

---

kafka-client/build.gradle.kts
kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/main/java/dev/responsive/kafka/api/config/ResponsiveConfig.java
kafka-client/src/main/java/dev/responsive/kafka/internal/config/ConfigUtils.java
kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/OtelMetricsService.java
kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/ResponsiveMetrics.java
kafka-client/src/main/resources/otel-jmx.config.yaml
kafka-client/src/test/java/dev/responsive/kafka/internal/metrics/EndOffsetsPollerTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/metrics/MetricPublishingCommitListenerTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/metrics/ResponsiveRestoreListenerTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/CommitBufferTest.java
responsive-test-utils/src/main/java/dev/responsive/kafka/internal/stores/TTDRestoreListener.java
settings.gradle.kts

I tested this with a local controller setup directly reporting to DD: https://us5.datadoghq.com/s/7d2b7ec4-e391-11ed-b891-da7ad0900005/iua-jdy-8wc
In a follow-up PR I'll modify `kafka-client-examples/simple-example` to run with agent-free metrics reporting.

Support for agent-free metrics reporting

---

operator/docker/Dockerfile
operator/src/main/helm/templates/deployment.yaml
operator/src/main/helm/values.yaml

- add a security context to the chart
- bump debian to 12 (bookworm)
- only install java into the final image

fix vulnerabilities in our operator image/chart

---

controller-api/src/main/proto/responsive/metrics/v1/metrics.proto

**NOTE:** this is backwards incompatible, but I've disabled metrics reporting and we can delete the kafka topics that had these keys since they were effectively a blackhole sink topic that wasn't being used yet.

strongly type our metrics export keys

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MetadataDoc.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoKVTable.java

for some reason, the previous code was generating `_id` clashes, this fixes it by just setting the `_id` to be the partition.
note (cc @ableegoldman) this is a breaking change that requires manual fix if you have anything that's deployed using Mongo reach out to me and we can migrate it.

fix mongo metadata table _id field

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/KVMetadataDoc.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoKVTable.java

Two changes in this PR:
1. Rename the MetadataDoc class to KVMetadataDoc to distinguish from the upcoming WindowDoc
2. Remove the redundant `"partition"` field but rename all the `"_id"` field variables as partition
For testing, in addition to the baseline tests, I also ran `ResponsiveKeyValueStoreRestoreIntegrationTest` with the storage backend set to Mongo. (As an aside, it would be nice to parametrize this test)

Rename MetadataDoc to KVMetadataDoc and use partition for _id field

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraTableSpecFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/PartitionedOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/SegmentedOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/TableName.java
kafka-client/src/test/java/dev/responsive/kafka/integration/TablePartitionerIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/CassandraFactTableIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/partitioning/SubPartitionerTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/utils/TableNameTest.java

Mongo limits database names to 65 characters (at the most -- may be even smaller in some cases) and also enforces the combined `<database_name>.<collection_name>` string to not exceed 128 characters. 
We should validate the table name length up front for fast-failure (I actually ran into this in a test with a long name). We should also remove the table name from the collection naming scheme for the MongoKVTable. We don't need to include the table name again since the collections are by definition scoped to that database, which is named after the state store. This way we are able to use up to the full allotted character count for table names (since otherwise the metadata collections could exceed 128 characters with a 64-character table name).

Use constant collection names and validate TableName length

---

kafka-client/src/main/java/dev/responsive/kafka/api/config/ResponsiveConfig.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/CommitBuffer.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/FlushTriggers.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/CommitBufferTest.java

adds a property that configures jitter around the flush interval to spread out load from flushes.

add flush jitter config

---

kafka-client/src/main/java/dev/responsive/kafka/api/config/ResponsiveConfig.java
kafka-client/src/main/java/dev/responsive/kafka/api/config/ResponsiveMode.java
kafka-client/src/main/java/dev/responsive/kafka/api/stores/ResponsiveKeyValueParams.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/PartitionedOperations.java

This patch starts the work to support running responsive in "migrate" mode,
which will be used to migrate apps to Responsive, or to a different Responsive
store. For now, all its used to do is enable a write optimization for TTL stores,
where we don't write records that are older than the TTL when the migration
started.

add an option for migration mode and avoid unnecessary ttl writes

---

kafka-client/src/test/java/dev/responsive/kafka/integration/TablePartitionerIntegrationTest.java

UPDATE: I think I figured out the test flakiness! It was previously reading uncommitted so there was a possibility that the data was pushed downstream but not yet committed.
----------
This test is flaky (need to figure out why) but anyway we should avoid having an NPE:
```
dev.responsive.kafka.integration.TablePartitionerIntegrationTest
✔ shouldFlushToRemoteTableWithSubpartitions() (6.5s)
✘ shouldFlushToRemoteTableWithoutSubpartitions() (5.8s)
java.lang.NullPointerException
at dev.responsive.kafka.integration.TablePartitionerIntegrationTest.shouldFlushToRemoteTableWithoutSubpartitions(TablePartitionerIntegrationTest.java:261)
```

avoid test NPE [minor]

---

.github/workflows/github-pr.yaml

```
Created stack 'system-tests-pub-pr-242'
Stack file exists. Won't initialize.
Previewing refresh (system-tests-pub-pr-242):
```

use pr # instead of branch name for pulumi stack

---

kafka-client/src/main/java/dev/responsive/kafka/internal/stores/PartitionedOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveStoreRegistration.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveStoreRegistry.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/SegmentedOperations.java
kafka-client/src/test/java/dev/responsive/kafka/integration/ResponsiveKeyValueStoreRestoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/clients/StoreCommitListenerTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/ResponsiveStoreRegistryTest.java
kafka-client/src/test/java/dev/responsive/kafka/testutils/IntegrationTestUtils.java

If changelogs started with non-O offsets, we would hit the exception below. This could happen if either:
1. the changelog is compacted and the compaction has removed the 0th offset
2. the changelog has retention and the 0th offset is beyond retention
This PR fixes this by forcing a call to `seekToBeginning` if the offsets in the metadata store are `NO_COMMITTED_OFFSET`.
```
[2024-02-23 11:11:48,494] WARN stream-thread [shouldflushstoresbeforeclosekeyvaluetrue-9a203ca0-f55a-4224-b171-9db93ff7d0fe-StreamThread-1] Encountered org.apache.kafka.clients.consumer.OffsetOutOfRangeException fetching records from restore consumer for partitions [shouldflushstoresbeforeclosekeyvaluetrue-shouldflushstoresbeforeclosekeyvaluetrueagg-changelog-0], it is likely that the consumer's position has fallen out …
```

fix restoration for changelogs that dont start at offset 0

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/BatchFlusher.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/CommitBuffer.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/CommitBufferTest.java

run `preFlush` and `postFlush` even if the actual data is empty - this only makes a difference in the bootstrapping tool where we filter TTL'd data as we process it

update offsets on flush even when buffer is empty

---

kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/exporter/otel/OtelMetricsService.java

Without this the `host.name` resource tag was not populated by the OTEL metrics exporter. This means that anything that aggregates by host would incorrectly aggregate metrics for every host by aggregating metrics for all hosts.
ex: if we had two hosts that were reporting 10 records/s, the metrics would consider both of them to be processing 20 records/s

add host.name to otel metrics

---

kafka-client-examples/simple-example/src/main/java/dev/responsive/examples/simpleapp/SimpleApplication.java
kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/main/java/dev/responsive/kafka/api/config/ResponsiveConfig.java
kafka-client/src/main/java/dev/responsive/kafka/internal/config/ConfigUtils.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraClient.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/DefaultCassandraClientFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/partitioning/SubPartitioner.java
kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/exporter/otel/OtelMetricsService.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/SessionUtil.java
kafka-client/src/test/java/dev/responsive/kafka/api/ResponsiveKafkaStreamsTest.java
kafka-client/src/test/java/dev/responsive/kafka/integration/ResponsiveKeyValueStoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/integration/ResponsiveKeyValueStoreRestoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/integration/TablePartitionerIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/CassandraClientTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/CassandraFactTableIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/CassandraKVTableIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoKVTableTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoSessionTableTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoWindowTableTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/partitioning/SubPartitionerTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/CommitBufferTest.java
kafka-client/src/test/java/dev/responsive/kafka/testutils/IntegrationTestUtils.java
kafka-client/src/test/java/dev/responsive/kafka/testutils/ResponsiveExtension.java
kafka-client/src/test/resources/CassandraDockerInit.cql
responsive-test-utils/src/main/java/dev/responsive/kafka/api/ResponsiveTopologyTestDriver.java

This PR attempts to clean up a bunch of configurations, most importantly along these two principles:
1. Any shared configurations between operator and `ResponsiveConfig` should have the same name
2. MongoDB/Cassandra configurations are no longer shared and are made explicit.
The following configurations were modified:
| old config | new config |
|------------|-------------|
| `responsive.storage.hostname` | `responsive.mongo.endpoint` for `MONGO_DB` stores and `repsonsive.cassandra.hostname` for `CASSANDRA` stores |
| `responsive.storage.port` | `responsive.cassandra.port` (Mongo stores do not require specifying a port) |
| `responsive.storage.datacenter` | `responsive.cassandra.datacenter` (Mongo stores do not require specifying a datacenter) |
| `responsive.tenant.id` | This …

[BREAKING CHANGE] refactor configurations into something coherent

---

kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/exporter/otel/OtelMetricsService.java

I was able to get the rough estimate of bytes over the wire by overwriting the default GrpcExporter: 70KB. The exporter exports the metrics every 10 seconds at the moment, leading to **18.7 GB / month / node**. I was able to confirm the order of magnitude with `netstat` statistics, which gave me something closer to 77 KB / 10s. 
This change turns on `gzip` compression at the exporter level, which reduces the over-the-wire bytes from 77 KB / 10s to about *17 KB / 10s*, a *78%* reduction to *4.5 GB / month / node*.

Metrics Exporting: Compress data on its way to the collector

---

kafka-client/src/main/java/dev/responsive/kafka/internal/stores/InjectedStoreArgs.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/PartitionedOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveStoreRegistration.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/SizeTrackingBuffer.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/PartitionedOperationsTest.java

This patch adds support for concurrent access to stores. After this change, we should be able to concurrently issue read calls to stores while other reads are happening, or while the main stream thread is doing put/delete or flushing.
First, we add a mechanism for injecting values into the store that can only be computed after the store has been initialized. We need to do this because the stores depend on some info that is made available only from the call to , which is kind of a quirk in streams (ideally, these things are just parameters to put/get/etc). In particular in today's implementation we depend on the processor context supplied in init to get the record's timestamp which we need for expiry calculation. This patch supports reading this from a reference to  in the store …

couple tweaks to support safe concurrent access to stores

---

controller-api/src/main/proto/responsive/controller/v1/controller.proto
operator/src/main/java/dev/responsive/controller/client/ControllerClient.java
operator/src/main/java/dev/responsive/controller/client/grpc/ControllerGrpcClient.java
operator/src/main/java/dev/responsive/k8s/controller/ControllerProtoFactories.java
operator/src/main/java/dev/responsive/k8s/operator/reconciler/ActionsWithTimestamp.java
operator/src/main/java/dev/responsive/k8s/operator/reconciler/KafkaStreamsPolicyPlugin.java
operator/src/main/java/dev/responsive/k8s/operator/reconciler/ResponsivePolicyReconciler.java
operator/src/test/java/dev/responsive/k8s/operator/reconciler/KafkaStreamsPolicyPluginTest.java
operator/src/test/java/dev/responsive/k8s/operator/reconciler/ResponsivePolicyReconcilerTest.java

This patch makes two related changes:
First, it adds APIs to the controller for serving and reporting the status of actions. The controller will use actions rather than target state to sync down commands. Actions are more flexible:
1. a given action only needs to specify the target state that pertains to the given action, rather than all target state.
2. actions don't need to be target-state based, but can be more traditional "commands", e.g. restart pod X
Second, it updates the operator to use the new actions APIs.

add actions api to controller and implement operator side

---

operator/src/main/helm/templates/appclusterrole.yaml
operator/src/main/java/dev/responsive/k8s/operator/reconciler/KafkaStreamsPolicyPlugin.java
operator/src/main/java/dev/responsive/k8s/operator/reconciler/ManagedApplication.java
operator/src/main/java/dev/responsive/k8s/operator/reconciler/ManagedDeployment.java
operator/src/main/java/dev/responsive/k8s/operator/reconciler/ManagedStatefulSet.java
operator/src/test/java/dev/responsive/k8s/operator/reconciler/KafkaStreamsPolicyPluginTest.java

This patch implements the operator changes required to execute an action that restarts a given pod.
Builds on #274

operator side changes for restarting a pod

---

controller-api/src/main/proto/responsive/controller/internal/v1/controller.proto
controller-api/src/main/proto/responsive/controller/internal/v1/internal.proto
controller-api/src/main/proto/responsive/controller/v1/controller.proto

This patch adds controller APIs for action management. We can
use these APIs to manually create and check the status of actions.
Builds on #275

Add controller apis for action management

---

kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/contexts/StreamThreadProcessorContext.java
kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/stores/AsyncTimestampedKeyValueStore.java
kafka-client/src/main/java/dev/responsive/kafka/api/stores/ResponsiveKeyValueBytesStoreSupplier.java
kafka-client/src/main/java/dev/responsive/kafka/api/stores/ResponsiveStores.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveTimestampedKeyValueStore.java
kafka-client/src/test/java/dev/responsive/kafka/async/AsyncProcessorIntegrationTest.java

Forgot to merge this with the async POC branch before merging that PR, so here's a quick followup that makes sure we actually use the TimestampedKeyValueStore in the async integration test.
I needed to make a few small changes to the way we build the normal (non-async) state stores for this to work, mot notably adding a ResponsiveTimestampedKeyValueStore that implements the TimestampedBytesStore marker interface in Streams. We actually had this a while back but I took it out to simplify things because we didn't strictly need it for plain Streams. Well, now we need it for the async processing stuff.
(If you're curious why we need it now, it's because we override the actual builder that adds the various store layers so that we can stick in our special async flushing layer to the async …

Use TimestampedKeyValueStore in AsyncProcessorIntegrationTest

---

kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncProcessor.java
kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/events/AsyncEvent.java
kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/queues/FinalizingQueue.java
kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/queues/ReadOnlyFinalizingQueue.java
kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/queues/SchedulingQueue.java
kafka-client/src/main/java/dev/responsive/kafka/api/config/ResponsiveConfig.java
kafka-client/src/test/java/dev/responsive/kafka/async/internals/queues/SchedulingQueueTest.java
kafka-client/src/test/java/dev/responsive/kafka/testutils/AsyncTestEvent.java

Introduced a new config for the max size of the per-key queues that make up the SchedulingQueue. 
We can follow up with the last config which controls the overall number of pending events (see #2 of [this comment](https://github.com/responsivedev/responsive-pub/pull/281#discussion_r1573018556))

Add per-key backpressure mechanism and unit tests for SchedulingQueue

---

kafka-client/src/test/java/dev/responsive/kafka/async/AsyncProcessorIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/testutils/SimpleStatefulProcessor.java
kafka-client/src/test/java/dev/responsive/kafka/testutils/SimpleStatefulProcessorSupplier.java

Tried to flush out the bug with not resetting the processor context after forwarding records but unfortunately(?) this test does seem to still be passing. Will try playing around with some of the parameters to see if I can hit it, but in the meantime, here's the expanded test.
Also has some refactoring/utilities lined up for some of the other testing I've been working on

Expand Async integration test with upstream and downstream stateful processors

---

kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncThreadPool.java

By default, the thread pool executor does not block when the queue is full. Moreover, it does not have an option to block. The best it supports is running the task on the main thread. The risk with blocking is that you could deadlock if all your processing threads are blocked. For streams, that's not as much of a concern because the thread will be removed from the group if that happens, and should only happen if the user's processor blocks. On the other hand, running from the main thread is not ideal because you could get unlucky and run a very slow task on the main thread and starve the topology. So instead, we wrap the pool in a semaphore to block before enqueuing a task

wrap thread pool in semaphore to block on full queue

---

kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncProcessor.java
kafka-client/src/test/java/dev/responsive/kafka/async/AsyncProcessorIntegrationTest.java

Make sure that when finalizing a record, we throw processing exceptions before preping the event for finalization. Also updates the test to check that the causing exception for injected exceptions is the injected exception.
Before this patch, all exceptions would result in an IllegalStateException due to event state machine violation.

make sure to throw processing exceptions before prep finalize

---

kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncProcessor.java
kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncThreadPool.java
kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/FatalAsyncException.java
kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/events/AsyncEvent.java
kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/queues/FinalizingQueue.java
kafka-client/src/test/java/dev/responsive/kafka/api/async/internals/AsyncThreadPoolTest.java
kafka-client/src/test/java/dev/responsive/kafka/testutils/AsyncTestEvent.java

Split up the error handling by separating into StreamsExceptions that arise from processing an event, and fatal exceptions that cover things like errors in the framework itself and checked exceptions.
Modified the async task from a Runnable to a Supplier<StreamsException> so we have a natural way to split up errors based on whether they're "normal" processing errors we can expect and handle (in which case we catch it and return it) vs uncaught/unexpected/checked exceptions that are immediately fatal.
Also split up the error handling path itself, so we don't add processing exceptions to the finalizing queue AND track them as an "uncaught AsyncThreadPool exception", it's either-or. This helps distinguish the fatal errors that should be acted upon immediately vs the non-fatal errors that …

Handle TaskMigratedException and clean up Throwables

---

kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncThreadPool.java
kafka-client/src/test/java/dev/responsive/kafka/api/async/internals/AsyncThreadPoolTest.java

This patch fixes how we deal with unexpected/fatal exception. Previously we were passing them through a completion stage generated by calling `handle` on the event's future. `handle` will not preserve the result and exception type of the original future. Instead, it's result/exception is the return value or exception thrown by the function passed to `handle`. Therefore unexpected exceptions passed to `handle` were being dropped. Instead, we use `whenComplete` which does preserve the exception.

deal with unexpected async exceptions from pool correctly

---

kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/stores/AsyncFlushingKeyValueStore.java
kafka-client/src/test/java/dev/responsive/kafka/api/async/internals/stores/AsyncFlushingKeyValueStoreTest.java

This patch makes store init more "transactional" by deregistering the flush listener if the wrapped store's init method throws. This way it either succeeds and the listener is registered and the store initialized. Or it fails and there is no listener registered.
If we dont do this, the task for which we threw can never be assigned to this stream thread again as it will always raise an IllegalStateException.

make sure to deregister listener when store init fails

---

kafka-client/src/main/java/dev/responsive/kafka/internal/clients/OffsetRecorder.java
kafka-client/src/main/java/dev/responsive/kafka/internal/clients/ResponsiveConsumer.java
kafka-client/src/test/java/dev/responsive/kafka/internal/clients/ResponsiveConsumerTest.java

This patch clears all recorded offsets in OffsetRecorder when Consumer.unsubscribe or RebalanceListener.handlePartitionsLost are called. In both cases, we know streams is reinitializing so we should clear any offsets we have recorded. If we don't clear them, then when streams finishes reinitializing and goes to do its first commit, it will try to find stores for those partitions and commit those offsets

clear recorded offsets on unsubscribe and handlePartitionsLost

---

kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncThreadPool.java
kafka-client/src/test/java/dev/responsive/kafka/api/async/internals/AsyncThreadPoolTest.java

We shouldn't record a CancellationException as a fatal async exception. The Async Thread Pool's future handler is called with a CancellationException whenever a task is cancelled, which is done on the normal path when a task is closed dirty. If we record the exception, then the next time the task is assigned we will immediately throw.

handle cancelled tasks in thread pool future handlers

---

kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/main/java/dev/responsive/kafka/api/stores/ResponsiveDslStoreSuppliers.java
kafka-client/src/main/java/dev/responsive/kafka/api/stores/ResponsiveSessionParams.java
kafka-client/src/main/java/dev/responsive/kafka/api/stores/ResponsiveStores.java
kafka-client/src/main/java/dev/responsive/kafka/internal/clients/DelegatingConsumer.java
kafka-client/src/main/java/dev/responsive/kafka/internal/clients/ResponsiveConsumer.java
kafka-client/src/main/java/dev/responsive/kafka/internal/clients/ResponsiveProducer.java
kafka-client/src/test/java/dev/responsive/kafka/integration/MinimalIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/integration/ResponsiveKafkaStreamsIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/testutils/IntegrationTestUtils.java
kafka-client/src/test/java/dev/responsive/kafka/testutils/ResponsiveExtension.java
kafka-client/src/test/java/org/apache/kafka/streams/processor/internals/GlobalStreamThreadIntegrationTest.java
settings.gradle.kts

This PR allows users to literally migrate with a single line code change by automatically configuring `ResponsiveKafkaStreams` to use the new `ResponsiveDslStoreSuppliers` class. The main change in this PR is in `kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java`. In order to use this we have to depend on apache kafka 3.7.
This PR also wires in Session stores, which previously did not have an equivalent store supplier in `Stores` static class. 
For testing, you can see that the new test doesn't specify any `Materialized` or `Stores` but it automatically populated data in MongoDB. The one drawback of this approach is that it risks collisions with names of stores in the same MongoDB instance. We need to figure out how to prevent that (perhaps by prepending the …

bump AK to 3.7 and default DSL stores to Responsive

---

kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/main/java/dev/responsive/kafka/api/config/StorageBackend.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/inmemory/InMemoryKVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/PartitionedOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/SessionClients.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/inmemory/InMemoryKVTableTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/testutils/Matchers.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/CommitBufferTest.java
responsive-test-utils/src/main/java/dev/responsive/kafka/api/ResponsiveTopologyTestDriver.java

Adds an in-memory responsive store type that stores all data in memory. It never stores an offset, so on a restore the entire store is restored from offset 0. This is meant to be used for test environments where we dont want to run a remote store.

add an in-memory responsive store tye

---

kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/e2etest/E2ETestDriver.java
kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/e2etest/Params.java

change the way the e2e test checks for stalls:
1. first it looks at the commit and end offsets of the sink, and looks for any keys that have been missed when the committed offset moves past the earliest unreceived input for that key
2. second, it looks for partitions that haven't made progress in a while

change the way e2e test checks for stalls

---

kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/main/java/dev/responsive/kafka/api/async/AsyncFixedKeyProcessorSupplier.java
kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncProcessor.java
kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncProcessorId.java
kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncThreadPool.java
kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncThreadPoolRegistration.java
kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncThreadPoolRegistry.java
kafka-client/src/main/java/dev/responsive/kafka/api/async/internals/AsyncUtils.java
kafka-client/src/main/java/dev/responsive/kafka/internal/clients/AsyncStreamsConsumer.java
kafka-client/src/main/java/dev/responsive/kafka/internal/clients/AsyncStreamsKafkaClientSupplier.java
kafka-client/src/main/java/dev/responsive/kafka/internal/clients/AsyncStreamsProducer.java
kafka-client/src/main/java/dev/responsive/kafka/internal/clients/DelegatingProducer.java
kafka-client/src/main/java/dev/responsive/kafka/internal/clients/ResponsiveConsumer.java
kafka-client/src/main/java/dev/responsive/kafka/internal/clients/ResponsiveKafkaClientSupplier.java
kafka-client/src/main/java/dev/responsive/kafka/internal/config/ConfigUtils.java
kafka-client/src/main/java/dev/responsive/kafka/internal/config/InternalSessionConfigs.java
kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/ResponsiveRestoreListener.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/CommitBuffer.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/Utils.java
kafka-client/src/test/java/dev/responsive/kafka/api/async/internals/AsyncThreadPoolTest.java
kafka-client/src/test/java/dev/responsive/kafka/async/AsyncProcessorIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/clients/ResponsiveConsumerTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/clients/ResponsiveKafkaClientSupplierTest.java
kafka-client/src/test/java/dev/responsive/kafka/testutils/IntegrationTestUtils.java

The general approach approach here is fairly straightforward: when there are no state stores we can use to hook into the `#flushCache` call before a commit, we simply hook into the actual clients' commit methods and flush the processors before proceeding with the commit. For ALOS apps, we flush via the consumer's `#commitSync` while with EOS we flush via the producer's `#commitTransaction`
To make this work cleanly, I extracted the async thread pool management from the ResponsiveKafkaClientSupplier/ResponsiveConsumer and put it into a new layer for all the async logic which only gets created when async processing is enabled. Similarly, we only create the async version of the relevant client and have it handle the async thread pool lifecycle -- in others, for EOS apps everything happens in …

Remove state store requirement for async processing

---

operator/build.gradle.kts
operator/src/main/java/dev/responsive/k8s/crd/ResponsivePolicySpec.java
operator/src/main/java/dev/responsive/k8s/operator/OperatorMain.java
operator/src/main/java/dev/responsive/k8s/operator/OperatorOptions.java
operator/src/main/java/dev/responsive/k8s/operator/reconciler/ResponsivePolicyReconciler.java
operator/src/test/java/dev/responsive/k8s/operator/OperatorE2EIntegrationTest.java
settings.gradle.kts

this patch allows running operator with `--labelSelector <label selector>` to specify which policies it should reconcile

allow deploying operators with labelselectors

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/KVDoc.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoKVTable.java
kafka-client/src/test/java/dev/responsive/kafka/integration/ResponsiveKeyValueStoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoKVTableTest.java

range scans on KV stores didn't consider kafka partition - this patch fixes it by adding the kafka partition into the data model. while I don't love this since it'll make it more difficult to repartition a kafka topic, it will only be the case for topologies that use range or all on KV stores (something the DSL does not leverage, so I consider it an advanced use case)

fix mongo KV range scans

---

responsive-spring/build.gradle.kts
responsive-spring/src/main/java/dev/responsive/spring/annotations/EnableResponsive.java
responsive-spring/src/main/java/dev/responsive/spring/annotations/ResponsiveDefaultConfiguration.java
responsive-spring/src/main/java/dev/responsive/spring/config/ResponsiveFactoryBean.java
responsive-spring/src/test/java/dev/responsive/spring/KafkaStreamsApp.java
settings.gradle.kts

See `KafkaStreamsApp` for how it's used. I tried many approaches to avoid copying a bunch of code over from the `spring-kafka` package and this was the best I could come up with.
I tried using bytecode manipulation, but turns out it's really difficult to replace a constructor call in Java -- so if I was going to override the entire `start` method in the bean I may as well just do what I did here so we have full control over it going forward.
I tested the basic functionality as well as the integration with other beans (like the DLQ bean) and it seems to work... difficult to tell what will break and what won't though!

initial commit for spring boot compatbility (JDK 17)

---

.github/actions/for-module-in-group/action.yaml
responsive-spring/build.gradle.kts

This uses the same mechanism we use to release the responsive-test-utils, which depends on a release of kafka-client, to ensure that `responsive-spring` artifacts are released in tandem with `kafka-client`

couple releases of kafka-client and responsive-spring

---

kafka-client/src/main/resources/otel-jmx.config.yaml

We are already collecting commit and send-offsets times, so we may as well include transaction initialization and abort.

Collect producer transaction init/abort metrics

---

.github/workflows/github-e2e-manual.yaml
.github/workflows/github-e2e-nightly.yaml
.github/workflows/github-e2e.yaml

Two new Antithesis custom params:
-database_type just determines which nodes get fault injection (mongo vs scylla)
-test_type is just used to gate test-specific assertions until we can migrate fully to the Java SDK

Add new custom Antithesis params and run mongo regression test in nightlies

---

kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/main/java/dev/responsive/kafka/api/config/ResponsiveConfig.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/SessionUtil.java
kafka-client/src/test/java/dev/responsive/kafka/integration/MinimalIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/integration/ResponsiveKafkaStreamsIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/integration/ResponsiveKeyValueStoreRestoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoKVTableTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoSessionTableTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoWindowTableTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoWindowedTableTest.java

Wanted to be able to set a higher connection idle timeout. Might as well take the opportunity to allow configuration of all the Mongo params via the connection string, rather than adding them one by one.
Context: saw this in an Antithesis run of the regression test:
```
org.apache.kafka.streams.errors.StreamsException: com.mongodb.MongoSocketReadException: Prematurely reached end of stream
```
According to some brief googling, this suggests the Mongo connection closed due to being idle. I'm guessing this is an effect of the chaos testing

Allow configuration of generic Mongo params via connection string

---

kafka-client-examples/e2e-test/build.gradle.kts
kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/common/UncaughtStreamsAntithesisHandler.java
kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/e2etest/E2ETestDriver.java
kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/regression/ResultsComparatorService.java
settings.gradle.kts

Beginning the migration to the new SDK for Antithesis. Mostly focusing on the new regression test in this PR and the `"ANTITHESIS NEVER"` string literals, will complete the migration in a followup PR to catch any remaining assertions from the async test

Use SDK for Antithesis tests

---

kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoTelemetryListener.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/ResponsiveMongoClient.java
kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/ResponsiveMetrics.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/SessionUtil.java
kafka-client/src/test/java/dev/responsive/kafka/integration/ResponsiveKafkaStreamsIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/integration/ResponsiveKeyValueStoreRestoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoKVTableTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoSessionTableTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoTelemetryListenerTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoWindowTableTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoWindowedTableTest.java

This patch adds collection of MongoDB command metrics. We implement a `CommandListener` as documented [here](https://www.mongodb.com/docs/drivers/java/sync/v4.6/fundamentals/monitoring/) which records counts and cumulative latencies for command successes and failures.

Collect MongoDB command execution metrics

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoTelemetryListener.java
kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/CassandraMetricsFactory.java
kafka-client/src/main/resources/otel-jmx.config.yaml
kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoTelemetryListenerTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/metrics/CassandraMetricsFactoryTest.java

This patch updates the OTEL configuration to include collection of MongoDB (#361) and Cassandra (#363) metrics.

Add Mongo/Cassandra metrics to otel config

---

kafka-client/src/main/java/dev/responsive/kafka/api/stores/ResponsiveKeyValueParams.java
kafka-client/src/main/java/dev/responsive/kafka/api/stores/ResponsiveSessionBytesStoreSupplier.java
kafka-client/src/main/java/dev/responsive/kafka/api/stores/ResponsiveStores.java
kafka-client/src/main/java/dev/responsive/kafka/api/stores/ResponsiveWindowBytesStoreSupplier.java
kafka-client/src/main/java/dev/responsive/kafka/api/stores/TtlProvider.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/RemoteTableSpecFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/PartitionedOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/StateDeserializer.java

First PR for row-level ttl. Includes only the API changes and supporting code

Row-level TTL PR 1: new API

---

kafka-client/src/main/java/dev/responsive/kafka/api/stores/ResponsiveKeyValueBytesStoreSupplier.java
kafka-client/src/main/java/dev/responsive/kafka/api/stores/TtlProvider.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraFactTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraKeyValueTable.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/CassandraFactTableIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/CassandraKVTableIntegrationTest.java

Quick followup to PR #2 (https://github.com/responsivedev/responsive-pub/pull/371) which switched the method of setting a ttl from the old Spec layers to the new TtlResolver. Carried over the ttl to the CassandraFactTable but forgot to apply it for the CassandraKeyValueTable, which is done in this PR

Row-level TTL PR 2.5: fix default ttl for CassandraKeyValueTable

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraFactTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraWindowedTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/ColumnName.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/CassandraFactTableIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/testutils/SerdeUtils.java

Implement row-level ttl for Scylla fact tables
PR 1: API https://github.com/responsivedev/responsive-pub/pull/370
PR 2: TtlResolver https://github.com/responsivedev/responsive-pub/pull/371
PR 3: compute minValidTs from TtlResolver https://github.com/responsivedev/responsive-pub/pull/373
Planned followup PRs (in order)
1. TopologyTestDriver
2. Mongo KV tables (insert/get/range/all)
Unplanned future work (can be picked up ad-hoc as needed)
1. Row-level ttl for Cassandra KVTables (insert/get/range/all)
2. Row-level ttl for in-memory KV tables
3. General ttl for global tables
4. Row-level ttl with migration mode

Row-level TTL PR 4: CassandraFactTable implementation

---

kafka-client/src/main/java/dev/responsive/kafka/api/stores/TtlProvider.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/GlobalOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/KVOperationsProvider.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/PartitionedOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveKeyValueStore.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/TtlResolver.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/StateDeserializer.java
kafka-client/src/main/java/org/apache/kafka/streams/state/internals/StoreAccessorUtil.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/CassandraFactTableIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/CassandraKVTableIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/ResponsiveKeyValueStoreTest.java
kafka-client/src/test/java/dev/responsive/kafka/testutils/IntegrationTestUtils.java

Avoid forcing the user to pass in their serdes again by extracting the StateSerdes from the MeteredKeyValueStore layer of the StateStore hierarchy.
Also addresses feedback from PR 4 to increase the ttl times used in the CassandraKV/FactTableIntegrationTest tests
PR 1: API https://github.com/responsivedev/responsive-pub/pull/370
PR 2: TtlResolver https://github.com/responsivedev/responsive-pub/pull/371
PR 3: compute minValidTs from TtlResolver https://github.com/responsivedev/responsive-pub/pull/373
PR 4: CassandraFactTable implementation https://github.com/responsivedev/responsive-pub/pull/374
Planned followup PRs (in order)
1. TopologyTestDriver <-- next/that before release cut
2. Mongo KV tables (insert/get/range/all)
Unplanned future work (can be picked up ad-hoc as needed)
1. …

Row-level TTL PR 5: automatically extract StateSerdes

---

kafka-client/src/main/java/dev/responsive/kafka/api/stores/ResponsiveKeyValueBytesStoreSupplier.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoKVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveKeyValueStore.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveSessionStore.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveTimestampedKeyValueStore.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveWindowStore.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/ResponsiveKeyValueStoreTest.java

Minor followup PR to the ttl stuff plus something I noticed while working on that. Threw it all in one PR:
1. Throw an exception if we see a standby task (we've now upgraded to a version of Streams with my patch for the standby-creation edge case so this should never happen)
2. Until we implement row-level ttl for MongoKVTable, we should throw an exception here too (since this might not happen right away)
3. Some minor cleanup left over after the StateSerde refactor

Throw exception on standbys and row-level ttl in MongoKVTable

---

responsive-test-utils/src/main/java/dev/responsive/kafka/api/ResponsiveTopologyTestDriver.java
responsive-test-utils/src/main/java/dev/responsive/kafka/internal/clients/TTDCassandraClient.java
responsive-test-utils/src/main/java/dev/responsive/kafka/internal/db/TTDKeyValueTable.java
responsive-test-utils/src/test/java/dev/responsive/kafka/api/ResponsiveTopologyTestDriverKeyValueStoreTest.java

Minor followup to [PR #6](https://github.com/responsivedev/responsive-pub/pull/376/files) where we changed the TTD so that only advancing stream-time by piping additional input records would apply ttl. Although this more closely matches how the TTD has to be used in vanilla Streams, it's a pain to be unable to advance the time on its own without being coupled to the input records. This PR restores the previous semantics of the ResponsiveTopologyTestDriver#advanceWallClockTime API so that this can be used to validate ttl in TTD tests
PR 1: API https://github.com/responsivedev/responsive-pub/pull/370
PR 2: TtlResolver https://github.com/responsivedev/responsive-pub/pull/371
PR 3: compute minValidTs from TtlResolver https://github.com/responsivedev/responsive-pub/pull/373
PR 4: …

Row-level TTL PR 7: TopologyTestDriver#advanceWallClockTime

---

kafka-client/src/main/java/dev/responsive/kafka/api/stores/TtlProvider.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/PartitionedOperations.java
kafka-client/src/test/java/dev/responsive/kafka/api/ResponsiveKeyValueParamsTest.java
kafka-client/src/test/java/dev/responsive/kafka/api/TtlProviderTest.java
kafka-client/src/test/java/dev/responsive/kafka/integration/RowLevelTtlIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/testutils/IntegrationTestUtils.java
responsive-test-utils/src/test/java/dev/responsive/kafka/api/ResponsiveTopologyTestDriverKeyValueStoreTest.java

This PR contains a small fix (more of a quality-of-life improvement for testing than a true bug) where we now advance stream-time during a `#get` operation, not only a `#put`, and expands the test coverage with unit tests for all the API classes and a full end-to-end integration test for the full feature.
PR 1: API https://github.com/responsivedev/responsive-pub/pull/370
PR 2: TtlResolver https://github.com/responsivedev/responsive-pub/pull/371
PR 3: compute minValidTs from TtlResolver https://github.com/responsivedev/responsive-pub/pull/373
PR 4: CassandraFactTable implementation https://github.com/responsivedev/responsive-pub/pull/374
PR 5: extract StateSerdes https://github.com/responsivedev/responsive-pub/pull/375
PR 6: support for ResponsiveTopologyTestDriver …

Row-level TTL PR 8: end-to-end integration test and advance stream-time during #get

---

operator/src/main/java/dev/responsive/k8s/crd/ResponsivePolicy.java
operator/src/main/java/dev/responsive/k8s/crd/kafkastreams/KafkaStreamsPolicySpec.java
operator/src/main/java/dev/responsive/k8s/operator/OperatorMain.java
operator/src/main/java/dev/responsive/k8s/operator/reconciler/ResponsivePolicyReconciler.java
operator/src/test/java/dev/responsive/k8s/operator/OperatorE2EIntegrationTest.java
operator/src/test/java/dev/responsive/k8s/operator/reconciler/KafkaStreamsPolicyPluginTest.java
settings.gradle.kts

This patch adds a validation rule to the CRD to validate that the max replicas is greater than the minReplicas. The bulk
of the patch is actually bumping the java operator SDK version to 4.9 so that we can get the ValidationRule annotation. The only functional change is the addition of the annotation to `KafkaStreamsPolicySpec`

validate that the maxReplicas field in the CRD is greater than minReplicas

---

kafka-client-examples/e2e-test/docker/antithesis/regression/config/docker-compose.yml.template
kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/regression/model/EnrichedOrder.java
kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/regression/tests/STJoinExample.java

Run the ST join test by default, and add a windowed store to the topology

Run more advanced regression test in Antithesis

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/spec/DefaultTableSpec.java

There was a regression in #371 where we started specifying LCS as the default compaction strategy. This change uses the cluster default instead, so that it will use ICS in scylla enterprise clusters (which ScyllaDB cloud are by default).
We can't test this easily since the scyllaDB public docker images don't have ICS, but I verified manually that this works.

use cluster default for compaction strategy

---

kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/regression/tests/STJoinExample.java

Played myself here by making the #1 most common mistake for Kafka Streams users: not realizing when/where you need to explicitly set serdes

Fix for Antithesis regression test

---

kafka-client/src/main/java/dev/responsive/kafka/api/config/ResponsiveConfig.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/RemoteTableSpecFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoKVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/ResponsiveMongoClient.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/RS3TableFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/spec/DefaultTableSpec.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/spec/RemoteTableSpec.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/GlobalOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/PartitionedOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/SegmentedOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/SessionOperationsImpl.java
kafka-client/src/test/java/dev/responsive/kafka/integration/ResponsiveKeyValueStoreRestoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/integration/TablePartitionerIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/CassandraFactTableIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/CassandraKVTableIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoKVTableTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/CommitBufferTest.java
kafka-client/src/test/java/dev/responsive/kafka/testutils/IntegrationTestUtils.java

Note that we still need to fix https://github.com/responsivedev/responsive-pub/issues/410

support configuring tombstone retention in Mongo

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraFactTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraKeyValueTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraWindowTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/FactSchemaWriter.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/LwtWriter.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/RemoteTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/RemoteWriter.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/inmemory/InMemoryKVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/KVDoc.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoKVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoSessionTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoWindowTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoWriter.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/RS3KVFlushManager.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/RS3KVTable.java
kafka-client/src/test/java/dev/responsive/kafka/async/AsyncProcessorIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/LwtWriterTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoKVTableTest.java
responsive-test-utils/src/main/java/dev/responsive/kafka/internal/db/TTDWindowTable.java
responsive-test-utils/src/main/java/dev/responsive/kafka/internal/db/TTDWriter.java

fixes #410 
Need to use Date instead of long for ttl to work, apparently
Since java just stores `Date` as an "epoch millis" long the only overhead is in creating the objects themselves, so it should be pretty minimal

Use Date format for TTL fields in Mongo tables

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraFactTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraKeyValueTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/RemoteKVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/inmemory/InMemoryKVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoKVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/RS3KVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/GlobalOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/KeyValueOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/PartitionedOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveKeyValueStore.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/Utils.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/CassandraKVTableIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/LwtWriterTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/inmemory/InMemoryKVTableTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/mongo/MongoKVTableTest.java
responsive-test-utils/src/main/java/dev/responsive/kafka/internal/db/TTDKeyValueTable.java

fixes #408 
Support prefix scans on:
- `CassandraKeyValueTable`
- `MongoKeyValueTable`
- `InMemoryKeyValueTable`
We don't support range scans on Global tables (yet), `CassandraFactTable` or `RS3KeyValueTable` yet.

support prefix scans in ResponsiveKeyValueStore

---

kafka-client/src/main/java/dev/responsive/kafka/api/config/ResponsiveConfig.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/RS3KVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/RS3TableFactory.java
kafka-client/src/test/java/dev/responsive/kafka/api/config/ResponsiveConfigTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/RS3TableFactoryTest.java

Add a new config `responsive.rs3.logical.store.mapping` which stores a static mapping from the table name to the RS3 logical store ID in the form `[t1]:[id1],[t2]:[id2]`.

RS3: Add static logical store mapping config

---

controller-api/build.gradle.kts
kafka-client/build.gradle.kts
kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/main/java/dev/responsive/kafka/api/config/ResponsiveConfig.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/RS3KVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/RS3TableFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/MeteredRS3Client.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/grpc/GrpcRS3Client.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/grpc/PssStubsProvider.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/grpc/middleware/PssHeadersInterceptor.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/metrics/RS3TableMetricsRecorder.java
kafka-client/src/main/java/dev/responsive/kafka/internal/metrics/ResponsiveMetrics.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/PartitionedOperations.java
kafka-client/src/main/resources/otel-jmx.config.yaml
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/RS3KVTableTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/RS3TableFactoryTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/client/grpc/GrpcRS3ClientTest.java
kafka-client/src/test/java/dev/responsive/kafka/testutils/ResponsiveExtension.java
operator/build.gradle.kts
operator/src/test/java/dev/responsive/controller/client/grpc/ControllerGrpcClientTest.java
settings.gradle.kts

some rs3 changes to get it going on the soak workload:
- adds tls support for the rs3 connection
- adds a metric that records the average get latency. This is done via a wrapper to the RS3 client so we can add more metrics easily later on.
- the rs3 protocol was updated to pass the pss/store id in headers, so we need to generate specific stubs for each pss (stubs are very cheap to create, and they all share a grpc channel). As such, the channel is moved into RemotePssStubsProvider, which now owns the channel and creates stubs for a given pss. When creating a stub, it adds an interceptor that adds the right headers for a given pss

rs3 changes for soak workload

---

kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/e2etest/E2ETestDriver.java

Currently startup events are spamming antithesis logs. We had a field `setupCompleteSignalFired` which was enabled to `false`, but never set to `true` after setup completed.

Fix spammy antithesis setup complete event

---

kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/main/java/dev/responsive/kafka/api/config/ResponsiveConfig.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/RS3TableFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/RS3Exception.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/RS3TimeoutException.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/grpc/GrpcRS3Client.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/RS3KVTableTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/RS3TableFactoryTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/client/grpc/GrpcRS3ClientTest.java

Get requests are probably the simplest to retry, so I've started there. This patch adds a new `responsive.rs3.retry.timeout.ms` and uses exponential backoff logic (borrowed from Kafka) to retry after UNAVAILABLE errors from the rs3 server.

Add retry logic for RS3 get/getoffsets requests

---

kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/e2etest/E2ETestDriver.java

This log message seems to be spamming the antithesis runs. Seems like this is a normal flow, so probably DEBUG is more appropriate.

Fix spammy warn message

---

kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/main/java/dev/responsive/kafka/api/config/ResponsiveConfig.java
kafka-client/src/test/java/dev/responsive/kafka/api/config/ResponsiveConfigTest.java

We defined the type of the rs3 retry timeout as long, but used `getInt` when accessing the property. This causes a `ClassCastException` which fails startup.

Fix incorrect type for rs3 retry timeout

---

kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/regression/RegressionSchema.java
kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/regression/model/GroupedOrder.java
kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/regression/model/Order.java
kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/regression/model/OrderMetadata.java
kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/regression/tests/KeyBatchExample.java

Should be merged by Thursday morning at the latest

Misc KeyBatchExample cleanup and improvements

---

kafka-client-examples/e2e-test/src/main/java/dev/responsive/examples/regression/tests/KeyBatchExample.java

Fixes a bug in the timestamp being used to determine flushing inside the KeyBatchExample's `#process`

Minor additional updates to KeyBatchExample

---

.github/workflows/github-e2e-logs.yaml

This patch adds a new action to download logs from a test run. The logs should be sent to the antithesis channel in slack the same way that we receive test reports.

Add action to get antithesis logs from a test run

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/MeteredRS3Client.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/RS3Client.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/Store.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/Table.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/grpc/GrpcRS3Client.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/grpc/PssStubsProvider.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/Utils.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/client/grpc/GrpcRS3ClientTest.java

Will add some tests to RS3KVTableIntegrationTest once the server-side changes are merged

Client-side support for ListStores API in RS3

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraWindowFlushManager.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/FlushManager.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/MongoWindowFlushManager.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/RemoteWindowTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/SegmentedWindowFlushManager.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/WindowFlushManager.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/RemoteWindowOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveWindowStore.java
responsive-test-utils/src/main/java/dev/responsive/kafka/internal/db/TTDWindowTable.java

The current `WindowFlushManager` is coupled with the segmenting approach even though it is not really used in `SegmentedOperations`. This patch moves `WindowFlushManager`to `SegmentedWindowFlushManager` and then reuses the `WindowFlushManager` name for an interface sitting between the two. I've also renamed `SegmentedOperations` to `RemoteWindowOperations` to reflect more general usage.

Separate segment window flush manager

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraFactFlushManager.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraFactTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraKVFlushManager.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraKeyValueTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraWindowFlushManager.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/CassandraWindowTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/MongoKVFlushManager.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/MongoSessionFlushManager.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/MongoWindowFlushManager.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/RemoteTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/inmemory/InMemoryKVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoKVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoSessionTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/mongo/MongoWindowTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/RS3KVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/GlobalOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/PartitionedOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/RemoteWindowOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/SessionOperationsImpl.java
kafka-client/src/test/java/dev/responsive/kafka/integration/ResponsiveKeyValueStoreRestoreIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/integration/TablePartitionerIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/CassandraFactTableIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/RS3KVTableIntegrationTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/stores/CommitBufferTest.java
responsive-test-utils/src/main/java/dev/responsive/kafka/internal/db/TTDTable.java

As suggested [here](https://github.com/responsivedev/responsive-pub/pull/443#discussion_r2027819702), `RemoteTable.fetchOffset` does not reflect its usage very clearly. In this patch, I've renamed it to `lastWrittenOffset`.

Rename fetchOffset to lastWrittenOffset

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/RS3KVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/RS3TableFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/CreateStoreTypes.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/Delete.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/MeteredRS3Client.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/Put.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/RS3Client.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/Range.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/grpc/GrpcKeyValueIterator.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/grpc/GrpcRS3Client.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/grpc/GrpcRangeRequestProxy.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/grpc/GrpcRs3Util.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/RS3TableFactoryTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/client/grpc/GrpcKeyValueIteratorTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/client/grpc/GrpcRS3ClientEndToEndTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/client/grpc/GrpcRS3ClientTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/client/grpc/GrpsRs3TestUtil.java

Updates the RS3 client for recent changes to the grpc schema.

Update rs3 proto

---

kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/main/java/dev/responsive/kafka/internal/license/LicenseUtils.java
kafka-client/src/test/java/dev/responsive/kafka/internal/license/LicenseUtilsTest.java

Currently we will not load a license if the API key is provided through `responsive.platform.api.key`. This patch changes the precedence to use this key as a fallback only if license loading fails. 
Additionally, we change RS3 initialization logic to not pass through an API key when the license is not `UsageBasedV1`.

Change license loading precedence

---

kafka-client/src/main/java/dev/responsive/kafka/api/ResponsiveKafkaStreams.java
kafka-client/src/main/java/dev/responsive/kafka/api/config/RS3ConfigSetter.java
kafka-client/src/main/java/dev/responsive/kafka/api/config/RS3StoreParams.java
kafka-client/src/main/java/dev/responsive/kafka/api/config/ResponsiveConfig.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/RS3TableFactory.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/RemoteWindowOperations.java
kafka-client/src/test/java/dev/responsive/kafka/api/config/ResponsiveConfigTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/RS3TableFactoryTest.java

Followup to https://github.com/responsivedev/responsive-pub/pull/453 to make the filterBitsPerKey (and any future rs3/storage related settings) configurable by users for individual stores

Introduce RS3ConfigSetter

---

kafka-client/build.gradle.kts
kafka-client/src/main/java/dev/responsive/kafka/internal/clients/StoreCommitListener.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/RemoteKVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/RS3KVTable.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/TableCheckpoint.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/LssId.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/MeteredRS3Client.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/PssCheckpoint.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/RS3Client.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/grpc/GrpcRS3Client.java
kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/grpc/GrpcRs3Util.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/PartitionedOperations.java
kafka-client/src/main/java/dev/responsive/kafka/internal/stores/ResponsiveStoreRegistration.java
kafka-client/src/main/java/dev/responsive/kafka/internal/utils/Utils.java
kafka-client/src/test/java/dev/responsive/kafka/internal/clients/StoreCommitListenerTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/RS3KVTableTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/TableCheckpointTest.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/client/grpc/GrpcRS3ClientTest.java
responsive-test-utils/src/main/java/dev/responsive/kafka/internal/clients/TTDCassandraClient.java

This patch adds wiring for taking checkpoints from ResponsiveKafkaStreams
- We implement the rs3 grpc client apis for taking checkpoints using the rs3 client
- The rs3 grpc client returns a `PssCheckpoint`, which the kv table aggregates into a `TableCheckpoint`. This type is then serialized and returned by `KVTable.checkpoint`
- `ResponsiveStoreRegistry` is extended to support taking checkpoints from registered stores

add wiring for creating checkpoints of responsive kv stores

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/client/grpc/WalEntryPutWriter.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/client/grpc/WalEntryPutWriterTest.java

Follow-up for https://github.com/responsivedev/rs3/pull/112. We added the `event_timestamp` to the window key value so that the server could track stream time for the purpose of TTL expiration. This patch passes through the timestamp in the GRPC API for writing segments.

Pass through event timestamp for windowed key values

---

kafka-client/src/main/java/dev/responsive/kafka/internal/db/rs3/RS3TableFactory.java
kafka-client/src/test/java/dev/responsive/kafka/internal/db/rs3/RS3TableFactoryTest.java

We used `WALL_CLOCK ` initially because rs3 didn't support stream time. Then I forgot to change it back after we finished implementing on the server.

Window stores should use stream time
